function InitVE() {
    Ext.define("OrdersEntity", {
        extend: "Ext.data.Model",
        fields: [{
            name: "OrdersID",
            type: "string"
        }, {
            name: "OrdersNo",
            type: "string"
        }, {
            name: "OrdersDate",
            type: "string"
        }, {
            name: "Payment",
            type: "string"
        }, {
            name: "PayType",
            type: "string"
        }, {
            name: "OrdersStatus",
            type: "string"
        }, {
            name: "OrdersStatusText",
            type: "string"
        }, {
            name: "StoreName",
            type: "string"
        }, {
            name: "RoomTypeName",
            type: "string"
        }, {
            name: "GuestName",
            type: "string"
        }, {
            name: "StartDate",
            type: "string"
        }, {
            name: "EndDate",
            type: "string"
        }, {
            name: "Remark",
            type: "string"
        }, {
            name: "RoomCount",
            type: "string"
        }, {
            name: "AllCount",
            type: "int"
        }, {
            name: "ApproveCount",
            type: "int"
        }, {
            name: "CheckCount",
            type: "int"
        }, {
            name: "CompleteCount",
            type: "int"
        }, {
            name: "CancelCount",
            type: "int"
        }, {
            name: "NotAuditCount",
            type: "int"
        }, {
            name: "VipID",
            type: "string"
        }]
        //, idProperty: 'OrdersID'
    });
}