//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JIT.CPOS.Web.SaturnServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SaturnServiceReference.SaturnServiceSoap")]
    public interface SaturnServiceSoap {
        
        // CODEGEN: Generating message contract since element name ReqContent from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAuthenticationCode", ReplyAction="*")]
        JIT.CPOS.Web.SaturnServiceReference.getAuthenticationCodeResponse getAuthenticationCode(JIT.CPOS.Web.SaturnServiceReference.getAuthenticationCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAuthenticationCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAuthenticationCode", Namespace="http://tempuri.org/", Order=0)]
        public JIT.CPOS.Web.SaturnServiceReference.getAuthenticationCodeRequestBody Body;
        
        public getAuthenticationCodeRequest() {
        }
        
        public getAuthenticationCodeRequest(JIT.CPOS.Web.SaturnServiceReference.getAuthenticationCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAuthenticationCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReqContent;
        
        public getAuthenticationCodeRequestBody() {
        }
        
        public getAuthenticationCodeRequestBody(string ReqContent) {
            this.ReqContent = ReqContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAuthenticationCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAuthenticationCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public JIT.CPOS.Web.SaturnServiceReference.getAuthenticationCodeResponseBody Body;
        
        public getAuthenticationCodeResponse() {
        }
        
        public getAuthenticationCodeResponse(JIT.CPOS.Web.SaturnServiceReference.getAuthenticationCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAuthenticationCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getAuthenticationCodeResult;
        
        public getAuthenticationCodeResponseBody() {
        }
        
        public getAuthenticationCodeResponseBody(string getAuthenticationCodeResult) {
            this.getAuthenticationCodeResult = getAuthenticationCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SaturnServiceSoapChannel : JIT.CPOS.Web.SaturnServiceReference.SaturnServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaturnServiceSoapClient : System.ServiceModel.ClientBase<JIT.CPOS.Web.SaturnServiceReference.SaturnServiceSoap>, JIT.CPOS.Web.SaturnServiceReference.SaturnServiceSoap {
        
        public SaturnServiceSoapClient() {
        }
        
        public SaturnServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SaturnServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaturnServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaturnServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JIT.CPOS.Web.SaturnServiceReference.getAuthenticationCodeResponse JIT.CPOS.Web.SaturnServiceReference.SaturnServiceSoap.getAuthenticationCode(JIT.CPOS.Web.SaturnServiceReference.getAuthenticationCodeRequest request) {
            return base.Channel.getAuthenticationCode(request);
        }
        
        public string getAuthenticationCode(string ReqContent) {
            JIT.CPOS.Web.SaturnServiceReference.getAuthenticationCodeRequest inValue = new JIT.CPOS.Web.SaturnServiceReference.getAuthenticationCodeRequest();
            inValue.Body = new JIT.CPOS.Web.SaturnServiceReference.getAuthenticationCodeRequestBody();
            inValue.Body.ReqContent = ReqContent;
            JIT.CPOS.Web.SaturnServiceReference.getAuthenticationCodeResponse retVal = ((JIT.CPOS.Web.SaturnServiceReference.SaturnServiceSoap)(this)).getAuthenticationCode(inValue);
            return retVal.Body.getAuthenticationCodeResult;
        }
    }
}
