//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.2012
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.2012 版自动生成。
// 
#pragma warning disable 1591

namespace JIT.CPOS.BS.WebServices.CustomerDataExchangeWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CustomerDataExchangeServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CustomerDataExchangeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SynUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback SynUnitOperationCompleted;
        
        private System.Threading.SendOrPostCallback SynTerminalOperationCompleted;
        
        private System.Threading.SendOrPostCallback CanAddUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback CanAddShopOperationCompleted;
        
        private System.Threading.SendOrPostCallback CanAddTerminalOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CustomerDataExchangeService() {
            this.Url = global::JIT.CPOS.BS.WebServices.Properties.Settings.Default.CPOS_BS_WebServices_CustomerDataExchangeWebService_CustomerDataExchangeService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SynUserCompletedEventHandler SynUserCompleted;
        
        /// <remarks/>
        public event SynUnitCompletedEventHandler SynUnitCompleted;
        
        /// <remarks/>
        public event SynTerminalCompletedEventHandler SynTerminalCompleted;
        
        /// <remarks/>
        public event CanAddUserCompletedEventHandler CanAddUserCompleted;
        
        /// <remarks/>
        public event CanAddShopCompletedEventHandler CanAddShopCompleted;
        
        /// <remarks/>
        public event CanAddTerminalCompletedEventHandler CanAddTerminalCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SynUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SynUser(string customerID, int typeID, string userInfo) {
            object[] results = this.Invoke("SynUser", new object[] {
                        customerID,
                        typeID,
                        userInfo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SynUserAsync(string customerID, int typeID, string userInfo) {
            this.SynUserAsync(customerID, typeID, userInfo, null);
        }
        
        /// <remarks/>
        public void SynUserAsync(string customerID, int typeID, string userInfo, object userState) {
            if ((this.SynUserOperationCompleted == null)) {
                this.SynUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSynUserOperationCompleted);
            }
            this.InvokeAsync("SynUser", new object[] {
                        customerID,
                        typeID,
                        userInfo}, this.SynUserOperationCompleted, userState);
        }
        
        private void OnSynUserOperationCompleted(object arg) {
            if ((this.SynUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SynUserCompleted(this, new SynUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SynUnit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SynUnit(string customerID, int typeID, string unitInfo) {
            object[] results = this.Invoke("SynUnit", new object[] {
                        customerID,
                        typeID,
                        unitInfo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SynUnitAsync(string customerID, int typeID, string unitInfo) {
            this.SynUnitAsync(customerID, typeID, unitInfo, null);
        }
        
        /// <remarks/>
        public void SynUnitAsync(string customerID, int typeID, string unitInfo, object userState) {
            if ((this.SynUnitOperationCompleted == null)) {
                this.SynUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSynUnitOperationCompleted);
            }
            this.InvokeAsync("SynUnit", new object[] {
                        customerID,
                        typeID,
                        unitInfo}, this.SynUnitOperationCompleted, userState);
        }
        
        private void OnSynUnitOperationCompleted(object arg) {
            if ((this.SynUnitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SynUnitCompleted(this, new SynUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SynTerminal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SynTerminal(string customerID, int typeID, string terminalInfo) {
            object[] results = this.Invoke("SynTerminal", new object[] {
                        customerID,
                        typeID,
                        terminalInfo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SynTerminalAsync(string customerID, int typeID, string terminalInfo) {
            this.SynTerminalAsync(customerID, typeID, terminalInfo, null);
        }
        
        /// <remarks/>
        public void SynTerminalAsync(string customerID, int typeID, string terminalInfo, object userState) {
            if ((this.SynTerminalOperationCompleted == null)) {
                this.SynTerminalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSynTerminalOperationCompleted);
            }
            this.InvokeAsync("SynTerminal", new object[] {
                        customerID,
                        typeID,
                        terminalInfo}, this.SynTerminalOperationCompleted, userState);
        }
        
        private void OnSynTerminalOperationCompleted(object arg) {
            if ((this.SynTerminalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SynTerminalCompleted(this, new SynTerminalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CanAddUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CanAddUser(string customerID) {
            object[] results = this.Invoke("CanAddUser", new object[] {
                        customerID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CanAddUserAsync(string customerID) {
            this.CanAddUserAsync(customerID, null);
        }
        
        /// <remarks/>
        public void CanAddUserAsync(string customerID, object userState) {
            if ((this.CanAddUserOperationCompleted == null)) {
                this.CanAddUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCanAddUserOperationCompleted);
            }
            this.InvokeAsync("CanAddUser", new object[] {
                        customerID}, this.CanAddUserOperationCompleted, userState);
        }
        
        private void OnCanAddUserOperationCompleted(object arg) {
            if ((this.CanAddUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CanAddUserCompleted(this, new CanAddUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CanAddShop", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CanAddShop(string customerID) {
            object[] results = this.Invoke("CanAddShop", new object[] {
                        customerID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CanAddShopAsync(string customerID) {
            this.CanAddShopAsync(customerID, null);
        }
        
        /// <remarks/>
        public void CanAddShopAsync(string customerID, object userState) {
            if ((this.CanAddShopOperationCompleted == null)) {
                this.CanAddShopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCanAddShopOperationCompleted);
            }
            this.InvokeAsync("CanAddShop", new object[] {
                        customerID}, this.CanAddShopOperationCompleted, userState);
        }
        
        private void OnCanAddShopOperationCompleted(object arg) {
            if ((this.CanAddShopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CanAddShopCompleted(this, new CanAddShopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CanAddTerminal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CanAddTerminal(string customerID) {
            object[] results = this.Invoke("CanAddTerminal", new object[] {
                        customerID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CanAddTerminalAsync(string customerID) {
            this.CanAddTerminalAsync(customerID, null);
        }
        
        /// <remarks/>
        public void CanAddTerminalAsync(string customerID, object userState) {
            if ((this.CanAddTerminalOperationCompleted == null)) {
                this.CanAddTerminalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCanAddTerminalOperationCompleted);
            }
            this.InvokeAsync("CanAddTerminal", new object[] {
                        customerID}, this.CanAddTerminalOperationCompleted, userState);
        }
        
        private void OnCanAddTerminalOperationCompleted(object arg) {
            if ((this.CanAddTerminalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CanAddTerminalCompleted(this, new CanAddTerminalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SynUserCompletedEventHandler(object sender, SynUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SynUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SynUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SynUnitCompletedEventHandler(object sender, SynUnitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SynUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SynUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SynTerminalCompletedEventHandler(object sender, SynTerminalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SynTerminalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SynTerminalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CanAddUserCompletedEventHandler(object sender, CanAddUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CanAddUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CanAddUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CanAddShopCompletedEventHandler(object sender, CanAddShopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CanAddShopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CanAddShopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CanAddTerminalCompletedEventHandler(object sender, CanAddTerminalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CanAddTerminalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CanAddTerminalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591