function InitVE() {
    Ext.define("OrderIntegralEntity", {
        extend: "Ext.data.Model",
        fields: [{
            name: "OrderIntegralID",
            type: "string"
        }, {
            name: "ItemID",
            type: "string"
        }, {
            name: "Quantity",
            type: "int"
        }, {
            name: "Integral",
            type: "string"
        }, {
            name: "IntegralAmmount",
            type: "string"
        }, {
            name: "VIPID",
            type: "string"
        }, {
            name: "LinkMan",
            type: "string"
        }, {
            name: "LinkTel",
            type: "string"
        }, {
            name: "CityID",
            type: "string"
        }, {
            name: "Address",
            type: "string"
        }, {
            name: "CreateBy",
            type: "string"
        }, {
            name: "CreateTime",
            type: "datetime"
        }, {
            name: "LastUpdateBy",
            type: "string"
        }, {
            name: "LastUpdateTime",
            type: "datetime"
        }, {
            name: "IsDelete",
            type: "int"
        }, {
            name: "item_name",
            type: "string"
        }, {
            name: "item_code",
            type: "string"
        }, {
            name: "VipName",
            type: "string"
        }, {
            name: "VipCode",
            type: "string"
        }, {
            name: "CreateTimeFormat",
            type: "string"
        }]
    });

}