function InitVE() {
    Ext.define("ReservationServiceScheduleEntity", {
        extend: "Ext.data.Model",
        fields: [{
            name: "ReservationServiceScheduleID",
            type: "string"
        }, {
            name: "ReservationServiceID",
            type: "int"
        }, {
            name: "ReservationServiceBigClassTermID",
            type: "int"
        }, {
            name: "ReservationServiceSmallClassTermID",
            type: "int"
        }, {
            name: "VIPID",
            type: "string"
        }, {
            name: "ReserveDate",
            type: "string"
        }, {
            name: "Remark",
            type: "string"
        }, {
            name: "PositionID",
            type: "int"
        }, {
            name: "ReserveTypeID",
            type: "int"
        }, {
            name: "StatusID",
            type: "int"
        }, {
            name: "ReservationStoreID",
            type: "int"
        }, {
            name: "CreateTime",
            type: "datetime"
        }, {
            name: "CreateBy",
            type: "string"
        }, {
            name: "LastUpdateTime",
            type: "datetime"
        }, {
            name: "LastUpdateBy",
            type: "string"
        }, {
            name: "IsDelete",
            type: "int"
        }]
    });
}