//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JIT.CPOS.BS.WebServices.AuthManagerWebServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthManagerWebServices.AuthServiceSoap")]
    public interface AuthServiceSoap {
        
        // CODEGEN: Generating message contract since element name token from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLoginUserInfo", ReplyAction="*")]
        JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetLoginUserInfoResponse GetLoginUserInfo(JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetLoginUserInfoRequest request);
        
        // CODEGEN: Generating message contract since element name customerID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerDBConnectionString", ReplyAction="*")]
        JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetCustomerDBConnectionStringResponse GetCustomerDBConnectionString(JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetCustomerDBConnectionStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoginUserInfo", Namespace="http://tempuri.org/", Order=0)]
        public JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetLoginUserInfoRequestBody Body;
        
        public GetLoginUserInfoRequest() {
        }
        
        public GetLoginUserInfoRequest(JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetLoginUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoginUserInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public GetLoginUserInfoRequestBody() {
        }
        
        public GetLoginUserInfoRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoginUserInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetLoginUserInfoResponseBody Body;
        
        public GetLoginUserInfoResponse() {
        }
        
        public GetLoginUserInfoResponse(JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetLoginUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoginUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLoginUserInfoResult;
        
        public GetLoginUserInfoResponseBody() {
        }
        
        public GetLoginUserInfoResponseBody(string GetLoginUserInfoResult) {
            this.GetLoginUserInfoResult = GetLoginUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerDBConnectionStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerDBConnectionString", Namespace="http://tempuri.org/", Order=0)]
        public JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetCustomerDBConnectionStringRequestBody Body;
        
        public GetCustomerDBConnectionStringRequest() {
        }
        
        public GetCustomerDBConnectionStringRequest(JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetCustomerDBConnectionStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerDBConnectionStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string customerID;
        
        public GetCustomerDBConnectionStringRequestBody() {
        }
        
        public GetCustomerDBConnectionStringRequestBody(string customerID) {
            this.customerID = customerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerDBConnectionStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerDBConnectionStringResponse", Namespace="http://tempuri.org/", Order=0)]
        public JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetCustomerDBConnectionStringResponseBody Body;
        
        public GetCustomerDBConnectionStringResponse() {
        }
        
        public GetCustomerDBConnectionStringResponse(JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetCustomerDBConnectionStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerDBConnectionStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCustomerDBConnectionStringResult;
        
        public GetCustomerDBConnectionStringResponseBody() {
        }
        
        public GetCustomerDBConnectionStringResponseBody(string GetCustomerDBConnectionStringResult) {
            this.GetCustomerDBConnectionStringResult = GetCustomerDBConnectionStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthServiceSoapChannel : JIT.CPOS.BS.WebServices.AuthManagerWebServices.AuthServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthServiceSoapClient : System.ServiceModel.ClientBase<JIT.CPOS.BS.WebServices.AuthManagerWebServices.AuthServiceSoap>, JIT.CPOS.BS.WebServices.AuthManagerWebServices.AuthServiceSoap {
        
        public AuthServiceSoapClient() {
        }
        
        public AuthServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetLoginUserInfoResponse JIT.CPOS.BS.WebServices.AuthManagerWebServices.AuthServiceSoap.GetLoginUserInfo(JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetLoginUserInfoRequest request) {
            return base.Channel.GetLoginUserInfo(request);
        }
        
        public string GetLoginUserInfo(string token) {
            JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetLoginUserInfoRequest inValue = new JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetLoginUserInfoRequest();
            inValue.Body = new JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetLoginUserInfoRequestBody();
            inValue.Body.token = token;
            JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetLoginUserInfoResponse retVal = ((JIT.CPOS.BS.WebServices.AuthManagerWebServices.AuthServiceSoap)(this)).GetLoginUserInfo(inValue);
            return retVal.Body.GetLoginUserInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetCustomerDBConnectionStringResponse JIT.CPOS.BS.WebServices.AuthManagerWebServices.AuthServiceSoap.GetCustomerDBConnectionString(JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetCustomerDBConnectionStringRequest request) {
            return base.Channel.GetCustomerDBConnectionString(request);
        }
        
        public string GetCustomerDBConnectionString(string customerID) {
            JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetCustomerDBConnectionStringRequest inValue = new JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetCustomerDBConnectionStringRequest();
            inValue.Body = new JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetCustomerDBConnectionStringRequestBody();
            inValue.Body.customerID = customerID;
            JIT.CPOS.BS.WebServices.AuthManagerWebServices.GetCustomerDBConnectionStringResponse retVal = ((JIT.CPOS.BS.WebServices.AuthManagerWebServices.AuthServiceSoap)(this)).GetCustomerDBConnectionString(inValue);
            return retVal.Body.GetCustomerDBConnectionStringResult;
        }
    }
}
