//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1022
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JIT.CPOS.BS.Web.MapKpiService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Threshold", Namespace="http://schemas.datacontract.org/2004/07/JIT.MapAnalysis.DataService.Contracts")]
    [System.SerializableAttribute()]
    public partial class Threshold : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string defaultcolorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string defaultimageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string defaultsizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string defaulttextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string levelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JIT.CPOS.BS.Web.MapKpiService.ThresholdItem[] thresholdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string defaultcolor {
            get {
                return this.defaultcolorField;
            }
            set {
                if ((object.ReferenceEquals(this.defaultcolorField, value) != true)) {
                    this.defaultcolorField = value;
                    this.RaisePropertyChanged("defaultcolor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string defaultimage {
            get {
                return this.defaultimageField;
            }
            set {
                if ((object.ReferenceEquals(this.defaultimageField, value) != true)) {
                    this.defaultimageField = value;
                    this.RaisePropertyChanged("defaultimage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string defaultsize {
            get {
                return this.defaultsizeField;
            }
            set {
                if ((object.ReferenceEquals(this.defaultsizeField, value) != true)) {
                    this.defaultsizeField = value;
                    this.RaisePropertyChanged("defaultsize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string defaulttext {
            get {
                return this.defaulttextField;
            }
            set {
                if ((object.ReferenceEquals(this.defaulttextField, value) != true)) {
                    this.defaulttextField = value;
                    this.RaisePropertyChanged("defaulttext");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string level {
            get {
                return this.levelField;
            }
            set {
                if ((object.ReferenceEquals(this.levelField, value) != true)) {
                    this.levelField = value;
                    this.RaisePropertyChanged("level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JIT.CPOS.BS.Web.MapKpiService.ThresholdItem[] threshold {
            get {
                return this.thresholdField;
            }
            set {
                if ((object.ReferenceEquals(this.thresholdField, value) != true)) {
                    this.thresholdField = value;
                    this.RaisePropertyChanged("threshold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThresholdItem", Namespace="http://schemas.datacontract.org/2004/07/JIT.MapAnalysis.DataService.Contracts")]
    [System.SerializableAttribute()]
    public partial class ThresholdItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string colorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string endField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string endlabelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string startField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string startlabelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textlabelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string color {
            get {
                return this.colorField;
            }
            set {
                if ((object.ReferenceEquals(this.colorField, value) != true)) {
                    this.colorField = value;
                    this.RaisePropertyChanged("color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string end {
            get {
                return this.endField;
            }
            set {
                if ((object.ReferenceEquals(this.endField, value) != true)) {
                    this.endField = value;
                    this.RaisePropertyChanged("end");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string endlabel {
            get {
                return this.endlabelField;
            }
            set {
                if ((object.ReferenceEquals(this.endlabelField, value) != true)) {
                    this.endlabelField = value;
                    this.RaisePropertyChanged("endlabel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string size {
            get {
                return this.sizeField;
            }
            set {
                if ((object.ReferenceEquals(this.sizeField, value) != true)) {
                    this.sizeField = value;
                    this.RaisePropertyChanged("size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string start {
            get {
                return this.startField;
            }
            set {
                if ((object.ReferenceEquals(this.startField, value) != true)) {
                    this.startField = value;
                    this.RaisePropertyChanged("start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string startlabel {
            get {
                return this.startlabelField;
            }
            set {
                if ((object.ReferenceEquals(this.startlabelField, value) != true)) {
                    this.startlabelField = value;
                    this.RaisePropertyChanged("startlabel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string textlabel {
            get {
                return this.textlabelField;
            }
            set {
                if ((object.ReferenceEquals(this.textlabelField, value) != true)) {
                    this.textlabelField = value;
                    this.RaisePropertyChanged("textlabel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KpiCategory", Namespace="http://schemas.datacontract.org/2004/07/JIT.MapAnalysis.DataService")]
    [System.SerializableAttribute()]
    public partial class KpiCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsDefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JIT.CPOS.BS.Web.MapKpiService.KPI[] KPIsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsDefault {
            get {
                return this.IsDefaultField;
            }
            set {
                if ((this.IsDefaultField.Equals(value) != true)) {
                    this.IsDefaultField = value;
                    this.RaisePropertyChanged("IsDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JIT.CPOS.BS.Web.MapKpiService.KPI[] KPIs {
            get {
                return this.KPIsField;
            }
            set {
                if ((object.ReferenceEquals(this.KPIsField, value) != true)) {
                    this.KPIsField = value;
                    this.RaisePropertyChanged("KPIs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KPI", Namespace="http://schemas.datacontract.org/2004/07/JIT.MapAnalysis.DataService")]
    [System.SerializableAttribute()]
    public partial class KPI : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsSupportSKUFilterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsSupportStoreFilterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsSupportTimeFilterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KPIIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KPILegendTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KPITextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointThresholdTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StyleCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StyleSubCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupportedLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ThresholdTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIDField, value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsSupportSKUFilter {
            get {
                return this.IsSupportSKUFilterField;
            }
            set {
                if ((this.IsSupportSKUFilterField.Equals(value) != true)) {
                    this.IsSupportSKUFilterField = value;
                    this.RaisePropertyChanged("IsSupportSKUFilter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsSupportStoreFilter {
            get {
                return this.IsSupportStoreFilterField;
            }
            set {
                if ((this.IsSupportStoreFilterField.Equals(value) != true)) {
                    this.IsSupportStoreFilterField = value;
                    this.RaisePropertyChanged("IsSupportStoreFilter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsSupportTimeFilter {
            get {
                return this.IsSupportTimeFilterField;
            }
            set {
                if ((this.IsSupportTimeFilterField.Equals(value) != true)) {
                    this.IsSupportTimeFilterField = value;
                    this.RaisePropertyChanged("IsSupportTimeFilter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KPIID {
            get {
                return this.KPIIDField;
            }
            set {
                if ((object.ReferenceEquals(this.KPIIDField, value) != true)) {
                    this.KPIIDField = value;
                    this.RaisePropertyChanged("KPIID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KPILegendText {
            get {
                return this.KPILegendTextField;
            }
            set {
                if ((object.ReferenceEquals(this.KPILegendTextField, value) != true)) {
                    this.KPILegendTextField = value;
                    this.RaisePropertyChanged("KPILegendText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KPIText {
            get {
                return this.KPITextField;
            }
            set {
                if ((object.ReferenceEquals(this.KPITextField, value) != true)) {
                    this.KPITextField = value;
                    this.RaisePropertyChanged("KPIText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PointThresholdType {
            get {
                return this.PointThresholdTypeField;
            }
            set {
                if ((this.PointThresholdTypeField.Equals(value) != true)) {
                    this.PointThresholdTypeField = value;
                    this.RaisePropertyChanged("PointThresholdType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StyleCode {
            get {
                return this.StyleCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StyleCodeField, value) != true)) {
                    this.StyleCodeField = value;
                    this.RaisePropertyChanged("StyleCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StyleSubCode {
            get {
                return this.StyleSubCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StyleSubCodeField, value) != true)) {
                    this.StyleSubCodeField = value;
                    this.RaisePropertyChanged("StyleSubCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SupportedLevel {
            get {
                return this.SupportedLevelField;
            }
            set {
                if ((this.SupportedLevelField.Equals(value) != true)) {
                    this.SupportedLevelField = value;
                    this.RaisePropertyChanged("SupportedLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ThresholdType {
            get {
                return this.ThresholdTypeField;
            }
            set {
                if ((this.ThresholdTypeField.Equals(value) != true)) {
                    this.ThresholdTypeField = value;
                    this.RaisePropertyChanged("ThresholdType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MapKpiService.IMapKpiService")]
    public interface IMapKpiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMapKpiService/GetAllCategories", ReplyAction="http://tempuri.org/IMapKpiService/GetAllCategoriesResponse")]
        System.Data.DataSet GetAllCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMapKpiService/GetThreshold", ReplyAction="http://tempuri.org/IMapKpiService/GetThresholdResponse")]
        JIT.CPOS.BS.Web.MapKpiService.Threshold GetThreshold();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMapKpiService/GetKpiByClientId", ReplyAction="http://tempuri.org/IMapKpiService/GetKpiByClientIdResponse")]
        JIT.CPOS.BS.Web.MapKpiService.KpiCategory[] GetKpiByClientId(string pClientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMapKpiService/GetKPIs", ReplyAction="http://tempuri.org/IMapKpiService/GetKPIsResponse")]
        System.Data.DataSet GetKPIs(int pCategoryID, string pKpiId, string pClientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMapKpiService/GetKpiDataByJsonParameter", ReplyAction="http://tempuri.org/IMapKpiService/GetKpiDataByJsonParameterResponse")]
        string GetKpiDataByJsonParameter(string pRequestJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMapKpiService/GetKpiData", ReplyAction="http://tempuri.org/IMapKpiService/GetKpiDataResponse")]
        string GetKpiData(int pLevel, string pPBoundId, string pKpiId, string pStyleCode, string pStyleSubCode, string[] pSkuId, string[] pSkuBrandId, string[] pSkuCategoryId, string[] pStoreIds, string[] pChannelId, string[] pChainId, string pDateFrom, string pDateTo, string pClientId, string pUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMapKpiService/GetKpiDataExportData", ReplyAction="http://tempuri.org/IMapKpiService/GetKpiDataExportDataResponse")]
        System.Data.DataTable GetKpiDataExportData(int pLevel, string pPBoundId, string pKpiId, string pStyleCode, string pStyleSubCode, string[] pSkuId, string[] pSkuBrandId, string[] pSkuCategoryId, string[] pStoreIds, string[] pChannelId, string[] pChainId, string pDateFrom, string pDateTo, string pClientId, string pUserId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMapKpiServiceChannel : JIT.CPOS.BS.Web.MapKpiService.IMapKpiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MapKpiServiceClient : System.ServiceModel.ClientBase<JIT.CPOS.BS.Web.MapKpiService.IMapKpiService>, JIT.CPOS.BS.Web.MapKpiService.IMapKpiService {
        
        public MapKpiServiceClient() {
        }
        
        public MapKpiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MapKpiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MapKpiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MapKpiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetAllCategories() {
            return base.Channel.GetAllCategories();
        }
        
        public JIT.CPOS.BS.Web.MapKpiService.Threshold GetThreshold() {
            return base.Channel.GetThreshold();
        }
        
        public JIT.CPOS.BS.Web.MapKpiService.KpiCategory[] GetKpiByClientId(string pClientId) {
            return base.Channel.GetKpiByClientId(pClientId);
        }
        
        public System.Data.DataSet GetKPIs(int pCategoryID, string pKpiId, string pClientId) {
            return base.Channel.GetKPIs(pCategoryID, pKpiId, pClientId);
        }
        
        public string GetKpiDataByJsonParameter(string pRequestJson) {
            return base.Channel.GetKpiDataByJsonParameter(pRequestJson);
        }
        
        public string GetKpiData(int pLevel, string pPBoundId, string pKpiId, string pStyleCode, string pStyleSubCode, string[] pSkuId, string[] pSkuBrandId, string[] pSkuCategoryId, string[] pStoreIds, string[] pChannelId, string[] pChainId, string pDateFrom, string pDateTo, string pClientId, string pUserId) {
            return base.Channel.GetKpiData(pLevel, pPBoundId, pKpiId, pStyleCode, pStyleSubCode, pSkuId, pSkuBrandId, pSkuCategoryId, pStoreIds, pChannelId, pChainId, pDateFrom, pDateTo, pClientId, pUserId);
        }
        
        public System.Data.DataTable GetKpiDataExportData(int pLevel, string pPBoundId, string pKpiId, string pStyleCode, string pStyleSubCode, string[] pSkuId, string[] pSkuBrandId, string[] pSkuCategoryId, string[] pStoreIds, string[] pChannelId, string[] pChainId, string pDateFrom, string pDateTo, string pClientId, string pUserId) {
            return base.Channel.GetKpiDataExportData(pLevel, pPBoundId, pKpiId, pStyleCode, pStyleSubCode, pSkuId, pSkuBrandId, pSkuCategoryId, pStoreIds, pChannelId, pChainId, pDateFrom, pDateTo, pClientId, pUserId);
        }
    }
}
