//var DetailData = {code:200,description:"操作成功",content:{hasUserAccount:"1",eventId:"121",title:"中欧国际工商学院首席营销官论坛（北京）---数字时代的营销变革",city:"上海",address:"北京市海淀区东北旺西路8号中关村软件园20号楼",contact:"苏小姐010-323232222",email:"alu156@126.com",imageUrl:"images/20130325130742.JPG",timeStr:"2013.3.30 13:00 --4.3 15:00",organizer:"中欧移动互联网协会/中欧电商协会",organizerType:'1',applyCount:"122",checkinCount:'100',buttonType:"1",applyStatus:0,payStatus:0,checkinStatus:"0",hasPrize:"0",intervalDays:"0",isCheckByBind:"1"}} ;
var DetailData = {"code":"200","description":"操作成功","content":{"hasUserAccount":"0","eventId":"11189","title":"中欧校友会上海分会(徐汇)成立大会将于6月16日召开","city":"上海","address":"上海市徐汇区徐家汇漕溪北路439号建国宾馆九州厅","contact":"周小姐、黄小姐","email":"null","imageUrl":"http://alumniapp.ceibs.edu:8080/ceibs/FileUploadServlet/upfiles/event_default.png","timeStr":"2013-06-16","organizer":"上海分会(徐汇)","organizerType":"1","applyCount":"11","checkinCount":"0","buttonType":"1","applyStatus":"false","payStatus":"1","feePaid":"0","feeNeed":"0","feeLeft":"0","checkinStatus":"false","isCheckByBind":"0","hasPrize":"0","intervalDays":"19","description":"花间堂•青尘院位于丽江市<div style='color:red'>古城区光义街忠义巷17移步易景，景景相透。客房内均配有地暖系统、高档卫浴设施、卫星电视及无线网络，在古朴典雅的纳西院落中，尽享清闲舒适的丽<江慢生活。青尘院的另一大特色便是她的自助厨房，借助临近忠义市场这一得天独厚的优势，采买最新鲜地道的当地食材<p>，亲自下<span>12321</span>厨一</span>展身手，绝对乐在其中。花间堂•青尘院位于丽江市古城区光义街忠义巷174号，毗邻丽江古城最具当地生活气息的集市——忠义市场，交<span>通出行十分便利，步行至著名景点木府也仅需3分钟。<\/br>青尘院由主院、辅院、后院三个院落组成，主院宽敞大气，辅院精巧别致，后院宁静优雅。18间精致、唯美的客房与自助餐厅、书房、影音室等公共空间分布其间，各种花卉树木错落环绕，郁郁葱葱，移步易景，景景相透。客房内均配有地暖系统、高档卫浴设施、卫星电视及无线网络，在古朴典雅的纳西院落中，尽享清闲舒适的丽江慢生活。青尘院的另一大特色便是她的自助厨房，借助临近忠义市场这一得天独厚的优势，采买最新鲜地道的当地食材，亲自下厨一展身手，绝对乐在其中。"}}
var Return_getAccountBind = {code:"200","description":"操作成功","content":{"hasBindWeixin":"1","userName":"asdasd","userId":"238869","isBindSucceed":"1"}};

var Return_login = {"code":"200","description":"操作成功","content":{"isBindSucceed":"1","userName":"eeee","userId":"238869"}}

var CheckInData = {"code":"200","description":"操作成功","content":{}};
var PriteListData = {"code":"200","content":{"hasPrizeOpen":"1","hasPrize":"1","prizeStatus":"0",'winPrizeName':"一等奖",'winPrizeId':"2","winPrizeDesc":"iPhone5手机","confirmed":"0","hasUserAccount":"1","myPrizes":[],"prizes":[{"imageUrl":"images/images.jpg","prizeDesc":"iPhone5手机","prizeId":"1","prizeName":"一等奖"},{"imageUrl":"images/images.jpg","prizeDesc":"Ipad mini平板电脑","prizeId":"2","prizeName":"二等奖"},{"imageUrl":"images/images.jpg","prizeDesc":"精美文房四宝套装","prizeId":"3","prizeName":"三等奖"}],"type":"0","winnerCount":"0","winners":[]},"description":"操作成功"};

var PriteListData1 = {"code":"200","content":{"hasPrizeOpen":"1","noBindText":"未绑定！","hasUserAccount":"1","myPrizes":[{"imageUrl":"http://i6.hexunimg.cn/2012-10-30/147380755.jpg","poolId":"1","prizeDesc":"奖品描述","prizeId":"1","prizeName":"奖品一"},{"imageUrl":"http://pic4.nipic.com/20091215/1546141_181058005434_2.jpg","poolId":"2","prizeDesc":"奖品描述","prizeId":"1","prizeName":"奖品二"},{"imageUrl":"http://i1.sinaimg.cn/IT/cr/2012/1206/2646343953.jpg","poolId":"3","prizeDesc":"奖品描述","prizeId":"1","prizeName":"奖品三"},{"imageUrl":"http://image.techweb.com.cn/upload/2012/1206/1354780499361.jpg","poolId":"4","prizeDesc":"奖品描述","prizeId":"1","prizeName":"奖品四"}],"prizes":[],"type":"1","winnerCount":"0","winners":[]},"description":"操作成功"};
var PriteListData2 = {"code":"200","content":{"hasPrizeOpen":"1","hasUserAccount":"1","myPrizes":[],"prizes":[],"type":"2","winnerCount":"0","isNext":"1","winners":[{"imageUrl":"images/example.jpg","timeStamp":"1223223232","userDesc":"昆山微讯网信息科技有限公司 ","userInfoEx":"EMBA09SH2","userName":"王孟孟 Vincent"},{"imageUrl":"http://i6.hexunimg.cn/2012-10-30/147380755.jpg","timeStamp":"1223223232","userDesc":"昆山微讯网信息科技有限公司网信息科技有限公司网信息科技有限公司 ","userInfoEx":"EMBA09SH2","userName":"王孟孟 Vincent"},{"imageUrl":"images/example.jpg","timeStamp":"1223223232","userDesc":"昆山微讯网信息科技有限公司网信息科技有限公司网信息科技有限公司 ","userInfoEx":"EMBA09SH2","userName":"王孟孟 Vincent"},{"imageUrl":"images/example.jpg","timeStamp":"1223223232","userDesc":"昆山微讯网信息科技有限公网信息科技有限公司网信息科技有限公司司 ","userInfoEx":"EMBA09SH2","userName":"王孟孟 Vincent"}]},"description":"操作成功"};

var HuDongData = {"code":"200","content":{"hasPollOpen":"0","hasUserAccount":"1","post":[]},"description":"操作成功"};

var ShopDetailData = {"code":"200","content":{"address":"云南省丽江市古城区光义街忠义巷174号","description":"花间堂•青尘院位于丽江市古城区光义街忠义巷174号，毗邻丽江古城最具当地生活气息的集市——忠义市场，交通出行十分便利，步行至著名景点木府也仅需3分钟。<\/br>青尘院由主院、辅院、后院三个院落组成，主院宽敞大气，辅院精巧别致，后院宁静优雅。18间精致、唯美的客房与自助餐厅、书房、影音室等公共空间分布其间，各种花卉树木错落环绕，郁郁葱葱，移步易景，景景相透。客房内均配有地暖系统、高档卫浴设施、卫星电视及无线网络，在古朴典雅的纳西院落中，尽享清闲舒适的丽江慢生活。青尘院的另一大特色便是她的自助厨房，借助临近忠义市场这一得天独厚的优势，采买最新鲜地道的当地食材，亲自下厨一展身手，绝对乐在其中。","imageUrl":"http://img1.qunarzz.com/wugc/p207/201305/15/743dcc658d3d878093835fbb.jpg_r_535x400x90_5a16d9ad.jpg","name":"花间堂丽江青尘院体验券","price":"780元/一晚","priceNow":"1元/一晚","telephone":"18988015030"},"description":"操作成功"};

var nearbyData = {"code":"200","content":{"users":[{"distance":"100米","imageUrl":"","tiemStr":"10秒钟前","userDesc":"昆山微讯网信息科技有限公司","userInfoEx":"EMBA08SH2","userName":"王孟孟 Vincent Wang"},{"distance":"1公里","imageUrl":"","tiemStr":"10分钟前","userDesc":"昆山微讯网信息科技有限公司22","userInfoEx":"EMBA08SH2","userName":"王孟孟22 Vincent Wang"},{"distance":"2公里","imageUrl":"","tiemStr":"2013-5-17 14:22","userDesc":"昆山微讯网信息科技有限公司33","userInfoEx":"EMBA08SH2","userName":"王孟孟33 Vincent Wang"},{"distance":"100m","imageUrl":"","tiemStr":"2天前","userDesc":"昆山微讯网信息科技有限公司44","userInfoEx":"EMBA08SH2","userName":"王孟孟44 Vincent Wang"},{"distance":"100m","imageUrl":"","tiemStr":"10秒钟前","userDesc":"昆山微讯网信息科技有限公司55","userInfoEx":"EMBA08SH2","userName":"王孟孟55 Vincent Wang"}]},"description":"操作成功"};
var ApplyData1 = {"code":"200","description":"操作成功","content":{"userName":"Mrs CHeng","className":"MTL2","mobile":"13816280305","email":"zhanzhongliang@weixun.co","questionCount":"4","questions":[
]}};



var ApplyData = {"code":"200","description":"操作成功","content":{"userName":"Mrs CHeng","className":"MTL2","mobile":"13816280305","email":"zhanzhongliang@weixun.co","questionCount":"4","questions":[


{"questionId":"111","questionText":"你的职业是？","questionType":"4","minSelected":"1","maxSelected":"1","isRequired":"0","isFinished":"0","options":[{"optionId":"40","optionText":"工程师","isSelected":"0"},{"optionId":"41","optionText":"商人","isSelected":"0"},{"optionId":"42","optionText":"自由职业者","isSelected":"0"},{"optionId":"43","optionText":"工作人员","isSelected":"0"},{"optionId":"44","optionText":"其他","isSelected":"1"}]},



]}};

var industryListData = {"code":"200","content":{"industries":[{"cname":"农林牧渔","ename":"Agriculture/Forestry/Fishing","industryId":"A:Agriculture"},{"cname":"采掘","ename":"Mining","industryId":"B:Mining"},{"cname":"制造","ename":"Manufacturing","industryId":"C:Manufacturing"},{"cname":"电力,煤气,水","ename":"Electric Power,Gas,Tap Water","industryId":"D:Electric Power,Gas,Tap Water"},{"cname":"建筑","ename":"Construction","industryId":"E:Construction"},{"cname":"交通,仓储","ename":"Transportation,Warehousing","industryId":"F:Transportation,Warehousing"},{"cname":"信息技术","ename":"Information Technology","industryId":"G:Information Technology"},{"cname":"批发,零售,贸易","ename":"Wholesale,Retail,Trade","industryId":"H:Wholesale,Retail,Trade"},{"cname":"金融,保险","ename":"Finance,Insurance","industryId":"I:Finance,Insurance"},{"cname":"房地产","ename":"Real Estate","industryId":"J:Real Estate"},{"cname":"社会服务","ename":"Social Services","industryId":"K:Social Services"},{"cname":"传播,文化","ename":"Media,Culture","industryId":"L:Media,Culture"},{"cname":"国家,政党机关,社会团体","ename":"Public Administration...","industryId":"M:Public Administration..."},{"cname":"教育,科研,体育","ename":"Education,Research,Sports","industryId":"N:Education,Research,Sports"},{"cname":"其他","ename":"Other","industryId":"Other:Other"},{"cname":"综合类","ename":"Miscellaneous","industryId":"Z:Miscellaneous"}]},"description":"操作成功"};
var SearchResultData = {"code":"200","content":{"isNext":"0", "users":[{"imageUrl":"http://www.vxinqing.com/productions/20130612055059576.jpgs_225.jpg","userDesc":"上海杰亦特信息科技有限公司","userInfoEx":"MBA071","userName":"- Andrew LEE"},{"imageUrl":"http://www.vxinqing.com/productions/20130612055059576.jpgs_225.jpg","userDesc":"上海杰亦特信息科技有限公司","userInfoEx":"MBA071","userName":"- Andrew LEE"},{"imageUrl":"http://www.vxinqing.com/productions/20130704131153611.jpgs_225.jpg","userDesc":"上海杰亦特信息科技有限公司","userInfoEx":"MBA071","userName":"- Andrew LEE"},{"imageUrl":"http://www.vxinqing.com/productions/20130612055059576.jpgs_225.jpg","userDesc":"上海杰亦特信息科技有限公司","userInfoEx":"MBA071","userName":"- Andrew LEE"},{"imageUrl":"http://www.vxinqing.com/productions/20130704131153611.jpgs_225.jpg","userDesc":"上海杰亦特信息科技有限公司","userInfoEx":"MBA071","userName":"- Andrew LEE"},{"imageUrl":"http://www.vxinqing.com/productions/20130612055059576.jpgs_225.jpg","userDesc":"上海杰亦特信息科技有限公司","userInfoEx":"MBA071","userName":"- Andrew LEE"},{"imageUrl":"http://www.vxinqing.com/productions/20130704131153611.jpgs_225.jpg","userDesc":"上海杰亦特信息科技有限公司","userInfoEx":"MBA071","userName":"- Andrew LEE"},{"imageUrl":"http://www.vxinqing.com/productions/20130612055059576.jpgs_225.jpg","userDesc":"上海杰亦特信息科技有限公司","userInfoEx":"MBA071","userName":"- Andrew LEE"},{"imageUrl":"http://www.vxinqing.com/productions/20130704131153611.jpgs_225.jpg","userDesc":"上海杰亦特信息科技有限公司","userInfoEx":"MBA071","userName":"- Andrew LEE"},{"imageUrl":"http://www.vxinqing.com/productions/20130612055059576.jpgs_225.jpg","userDesc":"上海杰亦特信息科技有限公司","userInfoEx":"MBA071","userName":"- Andrew LEE"}]},"description":"操作成功"}
var SearchNearbyData = {"code":"200","content":{"users":[{"distance":"12848.64","imageUrl":"http://www.vxinqing.com/productions/20130612055059576.jpgs_225.jpg","timeStr":"0分钟前","userDesc":"海润光伏科技股份有限公司","userInfoEx":"EMBA13SH2","userName":"邱新 QIU Xin"},{"distance":"12237.69","imageUrl":"http://Interact.ceibs.edu/AlumniMobileWebService/display_photo_a.jsp?id=jxiangfei.e07bj2&username=KyqUsZNnbGYGqnHhe3TlVA%3D%3D&sessionId=8XDt2krlcFp5Yklk3DbNZSpQAD%2FNMHR4","timeStr":"10分钟前","userDesc":"五八同城","userInfoEx":"EMBA07BJ2","userName":"贾向飞 Felix JIA"}]},"description":"操作成功"};


var GroupDetailData = {"code":"200","content":{"buttonType":"1","comingEventCount":"0","feeLeft":"0","feeNeed":"-1.0","feePaid":"","groupDescription":"中欧传媒业同学会是由中欧北方区传媒行业的学员和校友组成的同学组织，于2005年7月在北京正式成立，目前拥有会员80余人，其中包括电视台、报纸、杂志、网络、广告等多个领域的从业人士。在同学会中，校友们通过论坛、沙龙、访问等形式多样的活动，建立了相互沟通与交流、分享资源与经验、促进合作与发展的平台。俱乐部现有会员110余人。俱乐部活动包括：中国传媒产业高峰论坛（协办）、会员所在机构参观和传媒业校友论坛。  ","groupName":"中欧环保同学会  ","hasBindWeixin":"1","imageUrl":"http://alumniapp.ceibs.edu:8080/ceibs_test/FileUploadServlet/upfiles/group.png","isFree":"1","latestEventId":"","latestEventTitle":"","memberCount":"0","payStatus":"0","paymentDesc":"","userId":"238869"},"description":"操作成功"}

var ToJoinReturnData = {"code":"200","content":{"className":"","email":"","mobile":"","questionCount":"","questions":[],"userId":"","userName":""},"description":"操作成功"};

var GroupListData =  {"code":"200","content":{"isNext":"1", "groups":[{"imageUrl":"","groupName":"中欧高尔夫俱乐部","memberCount":"199","eventCount":"33","groupId":"22300"},{"imageUrl":"","groupName":"中欧高尔夫俱乐部","memberCount":"199","eventCount":"33","groupId":"22301"},{"imageUrl":"","groupName":"中欧高尔夫俱乐部","memberCount":"199","eventCount":"33","groupId":"22300"},{"imageUrl":"","groupName":"中欧高尔夫俱乐部","memberCount":"199","eventCount":"33","groupId":"22302"},{"imageUrl":"","groupName":"中欧高尔夫俱乐部","memberCount":"199","eventCount":"33","groupId":"22300"},{"imageUrl":"","groupName":"中欧高尔夫俱乐部","memberCount":"199","eventCount":"33","groupId":"22303"},{"imageUrl":"","groupName":"中欧高尔夫俱乐部","memberCount":"199","eventCount":"33","groupId":"22300"},{"imageUrl":"","groupName":"中欧高尔夫俱乐部","memberCount":"199","eventCount":"33","groupId":"22304"},{"imageUrl":"","groupName":"中欧高尔夫俱乐部","memberCount":"199","eventCount":"33","groupId":"22300"}]},"description":"操作成功"}

var GroupPersonData = {"code":"200","content":{"isNext":"1", "users":[{"imageUrl":"http://alumniapp.ceibs.edu:8083/46632563376dsaaaaaaaaa.jpg?x=1","userDesc":"上海杰亦特信息科技有限公司","userInfoEx":"MBA071","userName":"- Andrew LEE"},{"imageUrl":"","userDesc":"上海杰亦特信息科技有限公司","userInfoEx":"MBA071","userName":"- Andrew LEE"},{"imageUrl":"http://alumniapp.ceibs.edu:8080/ceibs/FileUploadServlet/upfiles/cjinyu.ex07_middle_1373636268774.jpg?x=1","userDesc":"上海杰亦特信息科技有限公司","userInfoEx":"MBA071","userName":"- Andrew LEE"},{"imageUrl":"http://www.vxinqing.com/productions/20130612055059576.jpgs_225.jpg","userDesc":"上海杰亦特信息科技有限公司","userInfoEx":"MBA071","userName":"- Andrew LEE"},{"imageUrl":"http://www.vxinqing.com/productions/20130704131153611.jpgs_225.jpg","userDesc":"上海杰亦特信息科技有限公司","userInfoEx":"MBA071","userName":"- Andrew LEE"},{"imageUrl":"http://www.vxinqing.com/productions/20130612055059576.jpgs_225.jpg","userDesc":"上海杰亦特信息科技有限公司","userInfoEx":"MBA071","userName":"- Andrew LEE"}]},"description":"操作成功"}


var getComingEventsForGroup = {"code":"200","content":{"events":[{"imageUrl":"http://www.vxinqing.com/productions/20130612055059576.jpgs_225.jpg","eventId":"1233","description":"音室等公共空间分布其间，各种花卉树木错落环绕，郁郁葱葱，移步易景，景景相透。客房内均配有地暖系统、高档卫浴设施、卫星电视及无线网络，在古朴典雅的纳西院落中，","title":"中欧移动互联网协会/中欧电商协会","startDate":"2013-06-23","endDate":"2013-06-23"},{"imageUrl":"http://alumniapp.ceibs.edu:8080/ceibs/FileUploadServlet/upfiles/event_default.png","eventId":"1233","description":"音室等公共空间分布其间，各种花卉树木错落环绕，郁郁葱葱，移步易景，景景相透。客房内均配有地暖系统、高档卫浴设施、卫星电视及无线网络，在古朴典雅的纳西院落中，","title":"中欧移动互联网协会/中欧电商协会","startDate":"2013-06-23","endDate":"2013-06-23"}]},"description":"操作成功"}