//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.1。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "apiSoap", Namespace = "http://10658.cc/")]
public partial class api : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback SendSmsOperationCompleted;

    private System.Threading.SendOrPostCallback SendMmsOperationCompleted;

    private System.Threading.SendOrPostCallback CreateMmsOperationCompleted;

    private System.Threading.SendOrPostCallback GetPidOperationCompleted;

    private System.Threading.SendOrPostCallback ChangePasswordOperationCompleted;

    private System.Threading.SendOrPostCallback GetNumOperationCompleted;

    private System.Threading.SendOrPostCallback VersionInfoOperationCompleted;

    /// <remarks/>
    public api()
    {
        this.Url = "http://10658.cc/webservice/api?Service";
    }

    /// <remarks/>
    public event SendSmsCompletedEventHandler SendSmsCompleted;

    /// <remarks/>
    public event SendMmsCompletedEventHandler SendMmsCompleted;

    /// <remarks/>
    public event CreateMmsCompletedEventHandler CreateMmsCompleted;

    /// <remarks/>
    public event GetPidCompletedEventHandler GetPidCompleted;

    /// <remarks/>
    public event ChangePasswordCompletedEventHandler ChangePasswordCompleted;

    /// <remarks/>
    public event GetNumCompletedEventHandler GetNumCompleted;

    /// <remarks/>
    public event VersionInfoCompletedEventHandler VersionInfoCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.xmlsoap.org/SendSms", RequestNamespace = "http://10658.cc/", ResponseNamespace = "http://10658.cc/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public SendSmsResult SendSms(string account, string password, string content, string mobile, string time, string pid)
    {
        object[] results = this.Invoke("SendSms", new object[] {
                    account,
                    password,
                    content,
                    mobile,
                    time,
                    pid});
        return ((SendSmsResult)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginSendSms(string account, string password, string content, string mobile, string time, string pid, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("SendSms", new object[] {
                    account,
                    password,
                    content,
                    mobile,
                    time,
                    pid}, callback, asyncState);
    }

    /// <remarks/>
    public SendSmsResult EndSendSms(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((SendSmsResult)(results[0]));
    }

    /// <remarks/>
    public void SendSmsAsync(string account, string password, string content, string mobile, string time, string pid)
    {
        this.SendSmsAsync(account, password, content, mobile, time, pid, null);
    }

    /// <remarks/>
    public void SendSmsAsync(string account, string password, string content, string mobile, string time, string pid, object userState)
    {
        if ((this.SendSmsOperationCompleted == null))
        {
            this.SendSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSmsOperationCompleted);
        }
        this.InvokeAsync("SendSms", new object[] {
                    account,
                    password,
                    content,
                    mobile,
                    time,
                    pid}, this.SendSmsOperationCompleted, userState);
    }

    private void OnSendSmsOperationCompleted(object arg)
    {
        if ((this.SendSmsCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendSmsCompleted(this, new SendSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.xmlsoap.org/SendMms", RequestNamespace = "http://10658.cc/", ResponseNamespace = "http://10658.cc/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public SendMmsResult SendMms(string account, string password, string mobile, string mmsid, string time, string pid)
    {
        object[] results = this.Invoke("SendMms", new object[] {
                    account,
                    password,
                    mobile,
                    mmsid,
                    time,
                    pid});
        return ((SendMmsResult)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginSendMms(string account, string password, string mobile, string mmsid, string time, string pid, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("SendMms", new object[] {
                    account,
                    password,
                    mobile,
                    mmsid,
                    time,
                    pid}, callback, asyncState);
    }

    /// <remarks/>
    public SendMmsResult EndSendMms(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((SendMmsResult)(results[0]));
    }

    /// <remarks/>
    public void SendMmsAsync(string account, string password, string mobile, string mmsid, string time, string pid)
    {
        this.SendMmsAsync(account, password, mobile, mmsid, time, pid, null);
    }

    /// <remarks/>
    public void SendMmsAsync(string account, string password, string mobile, string mmsid, string time, string pid, object userState)
    {
        if ((this.SendMmsOperationCompleted == null))
        {
            this.SendMmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMmsOperationCompleted);
        }
        this.InvokeAsync("SendMms", new object[] {
                    account,
                    password,
                    mobile,
                    mmsid,
                    time,
                    pid}, this.SendMmsOperationCompleted, userState);
    }

    private void OnSendMmsOperationCompleted(object arg)
    {
        if ((this.SendMmsCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendMmsCompleted(this, new SendMmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.xmlsoap.org/CreateMms", RequestNamespace = "http://10658.cc/", ResponseNamespace = "http://10658.cc/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public CreateMmsResult CreateMms(string account, string password, string title, string zipfile)
    {
        object[] results = this.Invoke("CreateMms", new object[] {
                    account,
                    password,
                    title,
                    zipfile});
        return ((CreateMmsResult)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginCreateMms(string account, string password, string title, string zipfile, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("CreateMms", new object[] {
                    account,
                    password,
                    title,
                    zipfile}, callback, asyncState);
    }

    /// <remarks/>
    public CreateMmsResult EndCreateMms(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((CreateMmsResult)(results[0]));
    }

    /// <remarks/>
    public void CreateMmsAsync(string account, string password, string title, string zipfile)
    {
        this.CreateMmsAsync(account, password, title, zipfile, null);
    }

    /// <remarks/>
    public void CreateMmsAsync(string account, string password, string title, string zipfile, object userState)
    {
        if ((this.CreateMmsOperationCompleted == null))
        {
            this.CreateMmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMmsOperationCompleted);
        }
        this.InvokeAsync("CreateMms", new object[] {
                    account,
                    password,
                    title,
                    zipfile}, this.CreateMmsOperationCompleted, userState);
    }

    private void OnCreateMmsOperationCompleted(object arg)
    {
        if ((this.CreateMmsCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateMmsCompleted(this, new CreateMmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.xmlsoap.org/GetPid", RequestNamespace = "http://10658.cc/", ResponseNamespace = "http://10658.cc/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public GetPidResult GetPid(string account, string password, string pname)
    {
        object[] results = this.Invoke("GetPid", new object[] {
                    account,
                    password,
                    pname});
        return ((GetPidResult)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginGetPid(string account, string password, string pname, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("GetPid", new object[] {
                    account,
                    password,
                    pname}, callback, asyncState);
    }

    /// <remarks/>
    public GetPidResult EndGetPid(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((GetPidResult)(results[0]));
    }

    /// <remarks/>
    public void GetPidAsync(string account, string password, string pname)
    {
        this.GetPidAsync(account, password, pname, null);
    }

    /// <remarks/>
    public void GetPidAsync(string account, string password, string pname, object userState)
    {
        if ((this.GetPidOperationCompleted == null))
        {
            this.GetPidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPidOperationCompleted);
        }
        this.InvokeAsync("GetPid", new object[] {
                    account,
                    password,
                    pname}, this.GetPidOperationCompleted, userState);
    }

    private void OnGetPidOperationCompleted(object arg)
    {
        if ((this.GetPidCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetPidCompleted(this, new GetPidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.xmlsoap.org/ChangePassword", RequestNamespace = "http://10658.cc/", ResponseNamespace = "http://10658.cc/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ChangePasswordResult ChangePassword(string account, string password, string newpassword)
    {
        object[] results = this.Invoke("ChangePassword", new object[] {
                    account,
                    password,
                    newpassword});
        return ((ChangePasswordResult)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginChangePassword(string account, string password, string newpassword, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("ChangePassword", new object[] {
                    account,
                    password,
                    newpassword}, callback, asyncState);
    }

    /// <remarks/>
    public ChangePasswordResult EndChangePassword(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((ChangePasswordResult)(results[0]));
    }

    /// <remarks/>
    public void ChangePasswordAsync(string account, string password, string newpassword)
    {
        this.ChangePasswordAsync(account, password, newpassword, null);
    }

    /// <remarks/>
    public void ChangePasswordAsync(string account, string password, string newpassword, object userState)
    {
        if ((this.ChangePasswordOperationCompleted == null))
        {
            this.ChangePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangePasswordOperationCompleted);
        }
        this.InvokeAsync("ChangePassword", new object[] {
                    account,
                    password,
                    newpassword}, this.ChangePasswordOperationCompleted, userState);
    }

    private void OnChangePasswordOperationCompleted(object arg)
    {
        if ((this.ChangePasswordCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ChangePasswordCompleted(this, new ChangePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.xmlsoap.org/GetNum", RequestNamespace = "http://10658.cc/", ResponseNamespace = "http://10658.cc/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public GetNumResult GetNum(string account, string password, string pid)
    {
        object[] results = this.Invoke("GetNum", new object[] {
                    account,
                    password,
                    pid});
        return ((GetNumResult)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginGetNum(string account, string password, string pid, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("GetNum", new object[] {
                    account,
                    password,
                    pid}, callback, asyncState);
    }

    /// <remarks/>
    public GetNumResult EndGetNum(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((GetNumResult)(results[0]));
    }

    /// <remarks/>
    public void GetNumAsync(string account, string password, string pid)
    {
        this.GetNumAsync(account, password, pid, null);
    }

    /// <remarks/>
    public void GetNumAsync(string account, string password, string pid, object userState)
    {
        if ((this.GetNumOperationCompleted == null))
        {
            this.GetNumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNumOperationCompleted);
        }
        this.InvokeAsync("GetNum", new object[] {
                    account,
                    password,
                    pid}, this.GetNumOperationCompleted, userState);
    }

    private void OnGetNumOperationCompleted(object arg)
    {
        if ((this.GetNumCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetNumCompleted(this, new GetNumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.xmlsoap.org/VersionInfo", RequestNamespace = "http://10658.cc/", ResponseNamespace = "http://10658.cc/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public VersionInfoResult VersionInfo()
    {
        object[] results = this.Invoke("VersionInfo", new object[0]);
        return ((VersionInfoResult)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginVersionInfo(System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("VersionInfo", new object[0], callback, asyncState);
    }

    /// <remarks/>
    public VersionInfoResult EndVersionInfo(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((VersionInfoResult)(results[0]));
    }

    /// <remarks/>
    public void VersionInfoAsync()
    {
        this.VersionInfoAsync(null);
    }

    /// <remarks/>
    public void VersionInfoAsync(object userState)
    {
        if ((this.VersionInfoOperationCompleted == null))
        {
            this.VersionInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVersionInfoOperationCompleted);
        }
        this.InvokeAsync("VersionInfo", new object[0], this.VersionInfoOperationCompleted, userState);
    }

    private void OnVersionInfoOperationCompleted(object arg)
    {
        if ((this.VersionInfoCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.VersionInfoCompleted(this, new VersionInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://10658.cc/")]
public partial class SendSmsResult
{

    private int codeField;

    private string msgField;

    private int smsidField;

    /// <remarks/>
    public int code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }

    /// <remarks/>
    public string msg
    {
        get
        {
            return this.msgField;
        }
        set
        {
            this.msgField = value;
        }
    }

    /// <remarks/>
    public int smsid
    {
        get
        {
            return this.smsidField;
        }
        set
        {
            this.smsidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://10658.cc/")]
public partial class VersionInfoResult
{

    private string msgField;

    /// <remarks/>
    public string msg
    {
        get
        {
            return this.msgField;
        }
        set
        {
            this.msgField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://10658.cc/")]
public partial class GetNumResult
{

    private int codeField;

    private string msgField;

    private int numField;

    /// <remarks/>
    public int code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }

    /// <remarks/>
    public string msg
    {
        get
        {
            return this.msgField;
        }
        set
        {
            this.msgField = value;
        }
    }

    /// <remarks/>
    public int num
    {
        get
        {
            return this.numField;
        }
        set
        {
            this.numField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://10658.cc/")]
public partial class ChangePasswordResult
{

    private int codeField;

    private string msgField;

    /// <remarks/>
    public int code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }

    /// <remarks/>
    public string msg
    {
        get
        {
            return this.msgField;
        }
        set
        {
            this.msgField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://10658.cc/")]
public partial class GetPidResult
{

    private int codeField;

    private string msgField;

    private int pidField;

    /// <remarks/>
    public int code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }

    /// <remarks/>
    public string msg
    {
        get
        {
            return this.msgField;
        }
        set
        {
            this.msgField = value;
        }
    }

    /// <remarks/>
    public int pid
    {
        get
        {
            return this.pidField;
        }
        set
        {
            this.pidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://10658.cc/")]
public partial class CreateMmsResult
{

    private int codeField;

    private string msgField;

    private int mmsidField;

    /// <remarks/>
    public int code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }

    /// <remarks/>
    public string msg
    {
        get
        {
            return this.msgField;
        }
        set
        {
            this.msgField = value;
        }
    }

    /// <remarks/>
    public int mmsid
    {
        get
        {
            return this.mmsidField;
        }
        set
        {
            this.mmsidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://10658.cc/")]
public partial class SendMmsResult
{

    private int codeField;

    private string msgField;

    private int mmsidField;

    /// <remarks/>
    public int code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }

    /// <remarks/>
    public string msg
    {
        get
        {
            return this.msgField;
        }
        set
        {
            this.msgField = value;
        }
    }

    /// <remarks/>
    public int mmsid
    {
        get
        {
            return this.mmsidField;
        }
        set
        {
            this.mmsidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void SendSmsCompletedEventHandler(object sender, SendSmsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SendSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal SendSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public SendSmsResult Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((SendSmsResult)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void SendMmsCompletedEventHandler(object sender, SendMmsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SendMmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal SendMmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public SendMmsResult Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((SendMmsResult)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void CreateMmsCompletedEventHandler(object sender, CreateMmsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreateMmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal CreateMmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public CreateMmsResult Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((CreateMmsResult)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void GetPidCompletedEventHandler(object sender, GetPidCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetPidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal GetPidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public GetPidResult Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((GetPidResult)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void ChangePasswordCompletedEventHandler(object sender, ChangePasswordCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal ChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public ChangePasswordResult Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((ChangePasswordResult)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void GetNumCompletedEventHandler(object sender, GetNumCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetNumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal GetNumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public GetNumResult Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((GetNumResult)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void VersionInfoCompletedEventHandler(object sender, VersionInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class VersionInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal VersionInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public VersionInfoResult Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((VersionInfoResult)(this.results[0]));
        }
    }
}
