function InitVE() {
    Ext.define("ActivityMediaEntity", {
        extend: "Ext.data.Model",
        fields: [{
            name: "ActivityMediaID",
            type: "string"
        }, {
            name: "MediaType",
            type: "int"
        }, {
            name: "MediaTypeText",
            type: "string"
        }, {
            name: "AttachmentID",
            type: "string"
        }, {
            name: "FileName",
            type: "string"
        }, {
            name: "MediaTitle",
            type: "string"
        }, {
            name: "Remark",
            type: "string"
        }, {
            name: "ActivityID",
            type: "string"
        }, {
            name: "ActivityTitle",
            type: "string"
        }, {
            name: "ClientID",
            type: "string"
        }, {
            name: "CreateTime",
            type: "datetime"
        }, {
            name: "CreateBy",
            type: "string"
        }, {
            name: "LastUpdateTime",
            type: "datetime"
        }, {
            name: "LastUpdateBy",
            type: "string"
        }, {
            name: "IsDelete",
            type: "int"
        }]
    });
}