/*
 jSmart Javascript template engine
 http://code.google.com/p/jsmart/

 Copyright 2011, Max Miroshnikov <miroshnikov at gmail dot com> 
 jSmart is licensed under the GNU General Public License
 http://www.apache.org/licenses/LICENSE-2.0
*/
(function(){function v(a,b){for(var c=2;c<arguments.length;++c)for(var d in arguments[c])if(typeof arguments[c][d]=="object"&&arguments[c][d]!=null){b[a+d]=arguments[c][d]instanceof Array?[]:{};v("",b[a+d],arguments[c][d])}else b[a+d]=arguments[c][d];return b}function F(a){var b=0,c;for(c in a)b++;return b}function s(a){return a.replace(/^\s+|\s+$/g,"").replace(/^['"]{1}|['"]{1}$/g,"")}function t(a,b){for(var c=0,d=0,e=jSmart.prototype.auto_literal,f=RegExp("^{ *("+a+") *}$","i"),g=0;g<b.length;++g)if(b.substr(g,
1)==jSmart.prototype.ldelim){if(!(e&&g+1<b.length&&" \n\r\t".indexOf(b[g+1])>=0)){if(!c){b=b.slice(g);d+=g;g=0}++c}}else if(b.substr(g,1)==jSmart.prototype.rdelim)if(!(e&&g-1>=0&&" \n\r\t".indexOf(b[g-1])>=0)){if(!--c){var h=b.slice(0,g+1).replace(/[\r\n]/g," ").match(f);if(h){h.index=d;return h}}if(c<0)c=0}return null}function B(a,b,c){var d="",e=null,f=null,g=0;do{if(e)g+=e[0].length;e=t(a,c);if(!e)throw Error("Unclosed {"+b+"}");d+=c.slice(0,e.index);g+=e.index;c=c.slice(e.index+e[0].length);if(f=
t(b,d))d=d.slice(f.index+f[0].length)}while(f);e.index=g;return e}function y(a,b,c,d){for(var e=0,f=t(c,d);f;f=t(c,d)){var g=t(a,d);if(!g||g.index>f.index){f.index+=e;return f}else{d=d.slice(g.index+g[0].length);e+=g.index+g[0].length;f=B(b,a,d);d=d.slice(f.index+f[0].length);e+=f.index+f[0].length}}return null}function G(a){return a.replace(/([$]\w+)@(index|iteration|first|last|show|total)/gi,"$1__$2")}function o(a,b){if(typeof a=="string")with(C)with(b)try{return eval(a)}catch(c){throw Error(c.message+
" in \n"+a);}return a}function H(a,b,c){with({__data:c,__v:b})if(a.match(/\[\]$/)){a=a.replace(/\[\]$/,"");eval("__data."+a+".push(__v)")}else eval("__data."+a+"=__v")}function i(a,b){for(var c=t(".+",a);c;c=t(".+",a)){c.index&&p(a.slice(0,c.index),b);a=a.slice(c.index+c[0].length);var d=c[1].match(/^\s*(\w+)(.*)$/);if(d){var e=d[1];d=d.length>2?d[2]:"";if(e in w){if(w[e].type=="block"){a=a.replace(/^\n/,"");c=B("/"+e,e+" +[^}]*",a);w[e].parse(d,b,a.slice(0,c.index));a=a.slice(c.index+c[0].length)}else{w[e].parse(d,
b);if(e=="extends")b=[]}a=a.replace(/^\n/,"")}else if(e in q){c=q[e];if(c.type=="block"){c=B("/"+e,e+" +[^}]*",a);d=l(d);var f=a.slice(0,c.index),g=[];b.push({type:"plugin",name:e,params:d,subTree:g});i(f,g);a=a.slice(c.index+c[0].length)}else c.type=="function"&&b.push({type:"plugin",name:e,params:l(d)})}else b.push(D(c[1]).tree)}else{b.push(D(c[1]).tree);if(b[b.length-1].name=="__operator"&&b[b.length-1].op=="=")a=a.replace(/^\n/,"")}}a&&p(a,b)}function p(a,b){if(p.parseEmbeddedVars)for(var c=/([$][\w@]+)|`([$][\w@]+(?:[.]\w+|\[(?:"[^"\\]*(?:\\.[^"\\]*)*"|'[^'\\]*(?:\\.[^'\\]*)*')?\])*)`/,
d=a.match(c);d;d=a.match(c)){b.push({type:"text",data:a.slice(0,d.index)});x(d[1]?d[1]:d[2],b);a=a.slice(d.index+d[0].length)}b.push({type:"text",data:a});return b}function x(a,b){b.push({type:"var",name:G(a)});return b}function I(a,b,c){c.push({type:"func",name:a,params:b});return c}function j(a,b,c,d){d.push({type:"build-in",name:"__operator",op:a,optype:b,precedence:c,params:{}})}function r(a,b){if(r.stop)return false;if(a.match(/^[|](\w+)(?:\s*(:)\s*)?/)&&(RegExp.$1 in C||RegExp.$1=="default"||
eval("typeof "+RegExp.$1)=="function")){b.value+=RegExp.lastMatch;var c=RegExp.$1;if(c=="default")c="defaultValue";a=a.slice(RegExp.lastMatch.length).replace(/^\s+/,"");r.stop=true;var d=l(RegExp.$2?a:"","\\s*:\\s*");r.stop=false;b.value+=d.str;d.unshift(b.token);d.__parsed.unshift(b.tree.pop());b.tree.push(I(c,d,[])[0]);a=a.slice(d.str.length);r(a,b);return true}return false}function L(a,b){if(!a)return false;if(r.stop&&b.tree.length)return false;if(a.match("^"+jSmart.prototype.ldelim)){var c=t(".*",
a);if(c){b.value+=c[0];i(c[0],b.tree);return true}}for(c=0;c<z.length;++c)if(a.match(RegExp("^"+z[c].re.source,"i"))){b.token=RegExp.lastMatch;b.value+=RegExp.lastMatch;z[c].parse(b,a.slice(b.token.length));return true}return false}function J(a,b,c){var d=b[a];if(d.name=="__operator"&&d.precedence==c){if(d.optype=="binary"){d.params.__parsed=[b[a-1],b[a+1]];b.splice(a-1,3,d);return true}else if(d.optype=="post-unary"){d.params.__parsed=[b[a-1]];b.splice(a-1,2,d);return true}d.params.__parsed=[b[a+
1]];b.splice(a,2,d)}return false}function K(a){var b=0;for(b=0;b<a.length;++b)if(a[b]instanceof Array)a[b]=K(a[b]);for(var c=1;c<14;++c)if(c==2||c==10)for(b=a.length;b>0;--b)b-=J(b-1,a,c);else for(b=0;b<a.length;++b)b-=J(b,a,c);return a[0]}function D(a){for(var b={value:"",tree:[]};L(a.slice(b.value.length),b););if(!b.tree.length)return false;b.tree=K(b.tree);return b}function l(a,b){var c=a.replace(/\n/g," ").replace(/^\s+|\s+$/g,""),d=[];d.__parsed=[];d.str="";if(!c)return d;var e=false;if(b)b=
RegExp("^"+b);else{b=/^\s+/;e=true}for(;c;){var f=null;if(e&&c.match(/^(\w+)\s*=\s*/)){f=RegExp.$1;d.str+=c.slice(0,RegExp.lastMatch.lengt);c=c.slice(RegExp.lastMatch.length)}var g=D(c);if(!g)break;if(f){d[f]=g.value;d.__parsed[f]=g.tree}else{d.push(g.value);d.__parsed.push(g.tree);if(isNaN(g.value)){d[g.value]=true;d.__parsed[g.value]=p("1",[])}}d.str+=c.slice(0,g.value.length);c=c.slice(g.value.length);if(c.match(b)){d.str+=c.slice(0,RegExp.lastMatch.length);c=c.slice(RegExp.lastMatch.length)}else break}return d}
function m(a,b){var c=[],d;for(d in a.__parsed)if(a.__parsed.hasOwnProperty(d)){var e=a.__parsed[d],f="";if(e.paramIsVar&&M(e.name,b))with(b)f=eval(e.name);else f=k([e],b);if(typeof f=="string"&&f.match(/^[1-9]\d*$/)&&!isNaN(f))f=parseInt(f);c[d]=f}c.__get=function(g,h){return g in c&&typeof c[g]!="undefined"?c[g]:h};return c}function M(a,b){if(!a.match(/^\s*[$]/))return false;try{with(b)eval(a)}catch(c){return false}return true}function k(a,b){for(var c="",d=0;d<a.length;++d){var e="",f=a[d];if(f.type==
"text")e=f.data;else if(f.type=="var")try{e=o(f.name,b)}catch(g){e=""}else if(f.type=="build-in")e=w[f.name].process(f,b);else if(f.type=="func"){e=m(f.params,b);for(var h=[],n=0;n<e.length;++n){h.push(f.name+"__p"+n);b[f.name+"__p"+n]=e[n]}e=o(f.name+"("+h.join(",")+")",b)}else if(f.type=="plugin"){h=q[f.name];if(h.type=="block"){h={value:true};for(q[f.name].process(m(f.params,b),"",b,h);h.value;){h.value=false;e+=q[f.name].process(m(f.params,b),k(f.subTree,b),b,h)}}else if(h.type=="function")e=
q[f.name].process(m(f.params,b),b)}if(typeof e=="boolean")e=e?"1":"";c+=e}return c}function E(a){for(var b="",c=a.match(/{\*/);c;c=a.match(/{\*/)){b+=a.slice(0,c.index);a=a.slice(c.index+c[0].length);c=a.match(/\*}/);if(!c)throw Error("Unclosed {*");a=a.slice(c.index+c[0].length);if(b.match(/\n+$/)&&a.match(/^\n+/)){b=b.replace(/\n+$/,"\n");a=a.replace(/^\n/,"")}}return b+a}var w={__quoted:{process:function(a,b){return m(a.params,b).join("")}},__operator:{process:function(a,b){var c=m(a.params,b);
b.__arg1=c[0];if(a.optype=="binary"){b.__arg2=c[1];if(a.op=="="){var d=a.params.__parsed[0].name;H(d,c[1],b);return""}else if(a.op.match(/(\+=|-=|\*=|\/=|%=)/)){d=a.params.__parsed[0].name;return o(d+a.op+"__arg2",b)}return o("__arg1 "+a.op+"__arg2",b)}else if(a.op=="!")return o("!__arg1",b);else{d=a.params.__parsed[0].type=="var"?a.params.__parsed[0].name:c[0];if(a.optype=="pre-unary")return o(a.op+d,b);else{if(a.op.match("even"))return o(d+"%2"+(a.op=="even_not"?"!=":"==")+"0",b);if(a.op.match("odd"))return o(d+
"%2"+(a.op=="odd_not"?"==":"!=")+"0",b);return o(d+a.op,b)}}}},section:{type:"block",parse:function(a,b,c){var d=[],e=[];b.push({type:"build-in",name:"section",params:l(a),subTree:d,subTreeElse:e});if(a=y("section [^}]+","/section","sectionelse",c)){i(c.slice(0,a.index),d);i(c.slice(a.index+a[0].length).replace(/^[\r\n]/,""),e)}else i(c,d)},process:function(a,b){var c=m(a.params,b);c.loop=o(a.params.loop,b);var d={};b.$smarty.section[c.name]=d;var e=c.__get("show",true);d.show=e;if(!e)return k(a.subTreeElse,
b);var f="";if(c.loop instanceof Object){if(this.foreach(c.name,c.__get("start",0),c.loop instanceof Array?c.loop.length:F(c.loop),c.__get("step",1),c.__get("max"),b,d,function(g){eval(c.name+" = "+g+";");f+=k(a.subTree,b)}))return f}else if(parseInt(c.loop))if(this.foreach(c.name,c.__get("start",0),parseInt(c.loop),c.__get("step",1),c.__get("max"),b,d,function(){f+=k(a.subTree,b)}))return f;return k(a.subTreeElse,b)},foreach:function(a,b,c,d,e,f,g,h){b=parseInt(b);c=parseInt(c);d=parseInt(d);e=parseInt(e);
if(isNaN(e))e=Number.MAX_VALUE;if(b<0){b=c+b;if(b<0)b=0}else if(b>=c)b=c?c-1:0;a=0;for(f=b;f>=0&&f<c&&a<e;f+=d,++a);g.total=a;g.loop=a;a=0;for(f=b;f>=0&&f<c&&a<e;f+=d,++a){g.first=f==b;g.last=f+d<0||f+d>=c;g.index=f;g.index_prev=f-d;g.index_next=f+d;g.iteration=g.rownum=a+1;h(f)}return a}},"for":{type:"block",parse:function(a,b,c){var d=a.match(/^\s*\$(\w+)\s*=\s*([^\s]+)\s*to\s*([^\s]+)\s*(?:step\s*([^\s]+))?\s*(.*)$/);if(!d)throw Error("Invalid {for} parameters: "+a);a=[];var e=[];b.push({type:"build-in",
name:"for",params:l("varName='"+d[1]+"' from="+d[2]+" to="+d[3]+" step="+(d[4]?d[4]:"1")+" "+d[5]),subTree:a,subTreeElse:e});if(b=y("for\\s[^}]+","/for","forelse",c)){i(c.slice(0,b.index),a);i(c.slice(b.index+b[0].length),e)}else i(c,a)},process:function(a,b){var c=m(a.params,b),d=parseInt(c.__get("from")),e=parseInt(c.__get("to")),f=parseInt(c.__get("step"));if(isNaN(f))f=1;var g=parseInt(c.__get("max"));if(isNaN(g))g=Number.MAX_VALUE;var h=0,n="";d=Math.min(Math.ceil(((f>0?e-d:d-e)+1)/Math.abs(f)),
g);for(e=parseInt(c.from);h<d;e+=f,++h){b["$"+c.varName]=e;n+=k(a.subTree,b)}h||(n=k(a.subTreeElse,b));return n}},"if":{type:"block",parse:function(a,b,c){var d=[],e=[];b.push({type:"build-in",name:"if",params:l(a),subTreeIf:d,subTreeElse:e});if(a=y("if\\s+[^}]+","/if","else[^}]*",c)){i(c.slice(0,a.index),d);c=c.slice(a.index+a[0].length);(d=a[1].match(/^elseif(.*)/))?w["if"].parse(d[1],e,c.replace(/^\n/,"")):i(c.replace(/^\n/,""),e)}else i(c,d)},process:function(a,b){return m(a.params,b)[0]?k(a.subTreeIf,
b):k(a.subTreeElse,b)}},foreach:{type:"block",parse:function(a,b,c){var d=null,e=null,f=null,g=null,h=a.match(/^\s*[$](\w+)\s*as\s*[$](\w+)\s*(=>\s*[$](\w+))?\s*$/i);if(h){d="$"+h[1];e=h[4]?h[4]:h[2];f=h[4]?h[2]:null}else{a=l(a);d=a.from;e=s(a.item);if("key"in a)f=s(a.key);if("name"in a)g=s(a.name)}a=[];h=[];b.push({type:"build-in",name:"foreach",arr:d,keyName:f,varName:"$"+e,loopName:g,subTree:a,subTreeElse:h});if(b=y("foreach\\s[^}]+","/foreach","foreachelse",c)){i(c.slice(0,b.index),a);i(c.slice(b.index+
b[0].length).replace(/^[\r\n]/,""),h)}else i(c,a)},process:function(a,b){var c=a.arr in b?b[a.arr]:s(a.arr);c instanceof Object||(c=[c]);var d=c instanceof Array?c.length:F(c);b[a.varName+"__total"]=d;if(a.loopName){b.$smarty.foreach[a.loopName]={};b.$smarty.foreach[a.loopName].total=d}var e="",f=0,g;for(g in c){if(c instanceof Array){g=parseInt(g);if(isNaN(g))continue}b[a.varName+"__key"]=g;if(a.keyName)b["$"+a.keyName]=b[a.varName+"__key"];b[a.varName]=c[g];b[a.varName+"__index"]=parseInt(f);b[a.varName+
"__iteration"]=parseInt(f+1);b[a.varName+"__first"]=f===0;b[a.varName+"__last"]=f==d-1;if(a.loopName){b.$smarty.foreach[a.loopName].index=parseInt(f);b.$smarty.foreach[a.loopName].iteration=parseInt(f+1);b.$smarty.foreach[a.loopName].first=f===0?1:"";b.$smarty.foreach[a.loopName].last=f==d-1?1:""}e+=k(a.subTree,b);++f}b[a.varName+"__show"]=f>0;if(a.loopName)b.$smarty.foreach[a.loopName].show=f>0?1:"";if(f>0)return e;return k(a.subTreeElse,b)}},"while":{type:"block",parse:function(a,b,c){var d=[];
b.push({type:"build-in",name:"while",params:l(a),subTree:d});i(c,d)},process:function(a,b){for(var c="";m(a.params,b)[0];)c+=k(a.subTree,b);return c}},capture:{type:"block",parse:function(a,b,c){var d=[];b.push({type:"build-in",name:"capture",params:l(a),subTree:d});i(c,d)},process:function(a,b){var c=m(a.params,b),d=k(a.subTree,b);b.$smarty.capture[c.__get("name","default")]=d;var e=c.__get("assign",null);if(e)b["$"+e]=d;if(c=c.__get("append",null)){c="$"+c;if(c in b)b[c]instanceof Array&&b[c].push(d);
else b[c]=[d]}return""}},"function":{type:"block",parse:function(a,b,c){a=l(a);b=[];var d=s(a.name);q[d]={type:"function",subTree:b,defautParams:a,process:function(e,f){var g=m(this.defautParams,f);delete g.name;return k(this.subTree,v("$",v("",{},f),g,e))}};i(c.replace(/\n+$/,""),b)}},php:{type:"block",parse:function(){}},javascript:{type:"block",parse:function(a,b,c){b.push({type:"build-in",name:"javascript",code:c})},process:function(a,b){o(a.code,b);return""}},include:{type:"function",parse:function(a,
b){b.push({type:"build-in",name:"include",params:l(a)})},process:function(a,b){var c=m(a.params,b),d=c.file;if(!(d in A)){A[d]=[];var e=jSmart.prototype.getTemplate(d);if(typeof e!="string")throw Error("No template for "+d);i(E(e.replace(/\r\n/g,"\n")),A[d])}d=k(A[d],v("$",v("",{},b),c));if("assign"in a.params){b["$"+c.assign]=d;return""}return d}},"extends":{type:"function",parse:function(a,b){var c=l(a);c=s(c.file);var d=jSmart.prototype.getTemplate(c);if(typeof d!="string")throw Error("No template for "+
c);i(E(d.replace(/\r\n/g,"\n")),b)}},block:{type:"block",parse:function(a,b,c){var d=l(a);b.push({type:"build-in",name:"block",params:d});if(!("append"in d))d.append=false;if(!("prepend"in d))d.prepend=false;d.hasChild=d.hasParent=false;a=x;x=function(e,f){if(e.match(/^\s*[$]smarty.block.child\s*$/))d.hasChild=true;if(e.match(/^\s*[$]smarty.block.parent\s*$/))d.hasParent=true;f.push({type:"var",name:G(e)});return f};b=[];i(c,b);x=a;c=s(d.name);c in u||(u[c]=[]);u[c].push({tree:b,params:d})},process:function(a,
b){b.$smarty.block.parent=b.$smarty.block.child="";var c=s(a.params.name);this.processBlocks(u[c],u[c].length-1,b);return b.$smarty.block.child},processBlocks:function(a,b,c){var d=true,e=false;for(b=b;b>=0;--b){if(a[b].params.hasParent){var f=c.$smarty.block.child;c.$smarty.block.child="";this.processBlocks(a,b-1,c);c.$smarty.block.parent=c.$smarty.block.child;c.$smarty.block.child=f}f=c.$smarty.block.child;var g=k(a[b].tree,c);c.$smarty.block.child=f;if(a[b].params.hasChild)c.$smarty.block.child=
g;else if(d)c.$smarty.block.child=g+c.$smarty.block.child;else if(e)c.$smarty.block.child+=g;d=a[b].params.append;e=a[b].params.prepend}}},eval:{type:"function",parse:function(a,b){b.push({type:"build-in",name:"eval",params:l(a)})},process:function(a,b){var c=m(a.params,b),d=[];i(c["var"],d);d=k(d,b);if(c=c.__get("assign",false))b["$"+c]=d;else return d;return""}},assign:{type:"function",parse:function(a,b){var c=l(a);b.push({type:"build-in",name:"assign",params:c})},process:function(a,b){var c=m(a.params,
b);H("$"+c.__get("var"),c.__get("value",""),b);return""}},append:{type:"function",parse:function(a,b){b.push({type:"build-in",name:"append",params:l(a)})},process:function(a,b){var c=m(a.params,b),d="$"+c["var"];if(!(d in b)||!(b[d]instanceof Array))b[d]=[];var e=c.__get("index",null);if(e)b[d][e]=c.value;else b[d].push(c.value);return""}},strip:{type:"block",parse:function(a,b,c){i(c.replace(/[ \t]*[\r\n]+[ \t]*/g,""),b)}},literal:{type:"block",parse:function(a,b,c){b.push({type:"text",data:c})}},
ldelim:{type:"function",parse:function(a,b){b.push({type:"text",data:jSmart.prototype.ldelim})}},rdelim:{type:"function",parse:function(a,b){b.push({type:"text",data:jSmart.prototype.rdelim})}}},q={},C={},A={},u=null,z=[{re:/[$][\w@]+(?:[.]\w+|\[(?:"[^"\\]*(?:\\.[^"\\]*)*"|'[^'\\]*(?:\\.[^'\\]*)*'|\d+|[$][\w@]+|\w+)?\])*/,parse:function(a,b){x(a.token,a.tree);a.tree[a.tree.length-1].paramIsVar=!r(b,a)}},{re:/(true|false)/,parse:function(a){p(a.token.match(/true/i)?"1":"",a.tree)}},{re:/'[^'\\]*(?:\\.[^'\\]*)*'/,
parse:function(a,b){p(eval(a.token),a.tree);r(b,a)}},{re:/"[^"\\]*(?:\\.[^"\\]*)*"/,parse:function(a,b){var c=eval(a.token),d=c.match(z[0].re);if(d&&d[0].length==c.length){x(c,a.tree);a.tree[a.tree.length-1].paramIsVar=!r(b,a)}else{d=[];p.parseEmbeddedVars=true;i(c,d);p.parseEmbeddedVars=false;d.length==1?a.tree.push(d[0]):a.tree.push({type:"build-in",name:"__quoted",params:{__parsed:d}});r(b,a)}}},{re:/(\w+)\s*[(]/,parse:function(a,b){a.value+=I(RegExp.$1,l(b,"\\s*,\\s*"),a.tree);if(b.match(/\s*[)]/))a.value+=
RegExp.lastMatch}},{re:/\s*\(\s*/,parse:function(a){var b=[];a.tree.push(b);b.parent=a.tree;a.tree=b}},{re:/\s*\)\s*/,parse:function(a){if(a.tree.parent)a.tree=a.tree.parent}},{re:/\s*(\+\+|--)\s*/,parse:function(a){a.tree.length&&a.tree[a.tree.length-1].type=="var"?j(RegExp.$1,"post-unary",1,a.tree):j(RegExp.$1,"pre-unary",1,a.tree)}},{re:/\s*(==|!=|===|!==)\s*/,parse:function(a){j(RegExp.$1,"binary",6,a.tree)}},{re:/\s+(eq|ne|neq)\s+/,parse:function(a){var b=RegExp.$1.replace(/ne(q)?/,"!=").replace(/eq/,
"==");j(b,"binary",6,a.tree)}},{re:/\s*!\s*/,parse:function(a){j("!","pre-unary",2,a.tree)}},{re:/\s+not\s+/,parse:function(a){j("!","pre-unary",2,a.tree)}},{re:/\s*(=|\+=|-=|\*=|\/=|%=)\s*/,parse:function(a){j(RegExp.$1,"binary",10,a.tree)}},{re:/\s*(\*|\/|%)\s*/,parse:function(a){j(RegExp.$1,"binary",3,a.tree)}},{re:/\s+mod\s+/,parse:function(a){j("%","binary",3,a.tree)}},{re:/\s*(\+|-)\s*/,parse:function(a){!a.tree.length||a.tree[a.tree.length-1].name=="__operator"?j(RegExp.$1,"pre-unary",4,a.tree):
j(RegExp.$1,"binary",4,a.tree)}},{re:/\s*(<|<=|>|>=|<>)\s*/,parse:function(a){j(RegExp.$1.replace(/<>/,"!="),"binary",5,a.tree)}},{re:/\s+(lt|lte|le|gt|gte|ge)\s+/,parse:function(a){var b=RegExp.$1.replace(/lt/,"<").replace(/l(t)?e/,"<=").replace(/gt/,">").replace(/g(t)?e/,">=");j(b,"binary",5,a.tree)}},{re:/\s+(is\s+(not\s+)?div\s+by)\s+/,parse:function(a){j(RegExp.$1,"binary",7,a.tree)}},{re:/\s+(is\s+(not\s+)?even(\s+by\s+)?)\s*/,parse:function(a){j(RegExp.$2?RegExp.$3?"even_by_not":"even_not":
RegExp.$3?"even_by":"even",RegExp.$3?"binary":"post-unary",7,a.tree)}},{re:/\s+(is\s+(not\s+)?odd(\s+by\s+)?)\s*/,parse:function(a){j(RegExp.$2?RegExp.$3?"odd_by_not":"odd_not":RegExp.$3?"odd_by":"odd",RegExp.$3?"binary":"post-unary",7,a.tree)}},{re:/\s*(&&)\s*/,parse:function(a){j(RegExp.$1,"binary",8,a.tree)}},{re:/\s*(\|\|)\s*/,parse:function(a){j(RegExp.$1,"binary",9,a.tree)}},{re:/\s+and\s+/,parse:function(a){j("&&","binary",11,a.tree)}},{re:/\s+xor\s+/,parse:function(a){j(RegExp.$1,"binary",
12,a.tree)}},{re:/\s+or\s+/,parse:function(a){j("||","binary",13,a.tree)}},{re:/\w+/,parse:function(a){p(RegExp.lastMatch,a.tree)}}];jSmart=function(a){this.tree=[];u=this.blocks={};i(E(a.replace(/\r\n/g,"\n")),this.tree)};jSmart.prototype.fetch=function(a){u=this.blocks;return k(this.tree,v("$",{},a,{smarty:{capture:{},foreach:{},section:{},block:{}}}))};jSmart.prototype.registerPlugin=function(a,b,c){if(a=="modifier")C[b]=c;else q[b]={type:a,process:c}};jSmart.prototype.getTemplate=function(a){throw Error("No template for "+
a);};jSmart.prototype.auto_literal=true;jSmart.prototype.ldelim="{";jSmart.prototype.rdelim="}";jSmart.prototype.registerPlugin("function","call",function(a,b){var c=a.name;delete a.name;var d=a.__get("assign",false);delete a.assign;c=q[c].process(a,b);if(d){b["$"+d]=c;return""}return c});jSmart.prototype.registerPlugin("function","counter",function(a,b){var c="__counter@"+a.__get("name","default");if(c in b){if("start"in a)b[c].value=parseInt(a.start);else{b[c].value=parseInt(b[c].value);b[c].skip=
parseInt(b[c].skip);if("down"==b[c].direction)b[c].value-=b[c].skip;else b[c].value+=b[c].skip}b[c].skip=a.__get("skip",b[c].skip);b[c].direction=a.__get("direction",b[c].direction);b[c].assign=a.__get("assign",b[c].assign)}else b[c]={value:parseInt(a.__get("start",1)),skip:parseInt(a.__get("skip",1)),direction:a.__get("direction","up"),assign:a.__get("assign",null)};if(b[c].assign){b["$"+b[c].assign]=b[c].value;return""}if(a.__get("print",true))return b[c].value;return""});jSmart.prototype.registerPlugin("function",
"cycle",function(a,b){var c="__cycle@"+a.__get("name","default");if(c in b){if(a.__get("advance","true"))b[c].i+=1;if(b[c].i>=b[c].arr.length||a.__get("reset",false))b[c].i=0}else{var d=[],e=a.values;if(e instanceof Object)for(nm in e)d.push(e[nm]);else{d=a.__get("delimiter",",");d=e.split(d)}b[c]={arr:d,i:0}}if(a.__get("assign",false)){b["$"+a.assign]=b[c].arr[b[c].i];return""}if(a.__get("print",true))return b[c].arr[b[c].i];return""});jSmart.prototype.registerPlugin("modifier","capitalize",function(a,
b){var c=RegExp(b?"[\\W\\d]+":"\\W+"),d=null,e="";for(d=a.match(c);d;d=a.match(c)){var f=a.slice(0,d.index);e+=f.match(/\d/)?f:f.charAt(0).toUpperCase()+f.slice(1);e+=a.slice(d.index,d.index+d[0].length);a=a.slice(d.index+d[0].length)}if(a.match(/\d/))return e+a;return e+a.charAt(0).toUpperCase()+a.slice(1)});jSmart.prototype.registerPlugin("modifier","cat",function(a,b){b=b?b:"";return a+b});jSmart.prototype.registerPlugin("modifier","count_characters",function(a,b){return b?a.length:a.replace(/\s/g,
"").length});jSmart.prototype.registerPlugin("modifier","count_paragraphs",function(a){if(a=a.match(/\n+/g))return a.length+1;return 1});jSmart.prototype.registerPlugin("modifier","count_sentences",function(a){if(a=a.match(/[^\s]\.(?!\w)/g))return a.length;return 0});jSmart.prototype.registerPlugin("modifier","count_words",function(a){if(a=a.match(/\w+/g))return a.length;return 0});jSmart.prototype.registerPlugin("modifier","defaultValue",function(a,b){return a&&a!="null"&&a!="undefined"?a:b?b:""});
jSmart.prototype.registerPlugin("modifier","indent",function(a,b,c){b=b?b:4;c=c?c:" ";for(var d="";b--;)d+=c;b=a.match(/\n+$/);return d+a.replace(/\n+$/,"").replace(/\n/g,"\n"+d)+(b?b[0]:"")});jSmart.prototype.registerPlugin("modifier","lower",function(a){return a.toLowerCase()});jSmart.prototype.registerPlugin("modifier","nl2br",function(a){return a.replace(/\n/g,"<br />\n")});jSmart.prototype.registerPlugin("modifier","regex_replace",function(a,b,c){b=b.match(/^ *\/(.*)\/(.*) *$/);return(new String(a)).replace(RegExp(b[1],
"g"+(b.length>1?b[2]:"")),c)});jSmart.prototype.registerPlugin("modifier","replace",function(a,b,c){if(!b)return a;a=new String(a);var d="",e=-1;for(e=a.indexOf(b,e);e>=0;e=a.indexOf(b,e)){d+=a.slice(0,e)+c;e+=b.length;a=a.slice(e)}return d+a});jSmart.prototype.registerPlugin("modifier","spacify",function(a,b){b||(b=" ");return a.replace(/(\n|.)(?!$)/g,"$1"+b)});jSmart.prototype.registerPlugin("modifier","strip",function(a,b){b=b?b:" ";return(new String(a)).replace(/[\s]+/g,b)});jSmart.prototype.registerPlugin("modifier",
"strip_tags",function(a,b){b=b==null?true:b;return(new String(a)).replace(/<[^>]*?>/g,b?" ":"")});jSmart.prototype.registerPlugin("modifier","truncate",function(a,b,c,d,e){b=b?b:80;c=c!=null?c:"...";if(a.length<=b)return a;b-=Math.min(b,c.length);if(e)return a.slice(0,Math.floor(b/2))+c+a.slice(a.length-Math.floor(b/2));d||(a=a.slice(0,b+1).replace(/\s+?(\S+)?$/,""));return a.slice(0,b)+c});jSmart.prototype.registerPlugin("modifier","upper",function(a){return a.toUpperCase()});jSmart.prototype.registerPlugin("modifier",
"wordwrap",function(a,b,c,d){b=b?b:80;c=c?c:"\n";b-=Math.min(b,c.length);a=a.split("\n");var e=0;for(e=0;e<a.length;++e){for(var f=a[e],g="",h=0;h+b<f.length;){var n=f.slice(h,h+b+1);d||(n=n.replace(/(\s+)\S+$/,"$1"));n=n.slice(0,b);h+=n.length;for(g+=n.replace(/\s+$/,"").replace(/^\s+/,"")+c;f.charAt(h).match(/\s/);)++h}a[e]=g+f.slice(h)}return a.join("\n")});String.prototype.fetch=function(a){return(new jSmart(this)).fetch(a)}})();
