function InitVE() {
    Ext.define("TaskViewEntity", {
        extend: "Ext.data.Model",
        fields: [{
            name: "VisitingTaskID",
            type: "string"
        }, {
            name: "VisitingTaskNo",
            type: "string"
        }, {
            name: "VisitingTaskName",
            type: "string"
        }, {
            name: "VisitingTaskType",
            type: "int"
        }, {
            name: "ClientPositionID",
            type: "int"
        }, {
            name: "POPType",
            type: "int"
        }, {
            name: "StartDate",
            type: "datetime",
            dataFormat:"c"
        }, {
            name: "EndDate",
            type: "datetime",
            dataFormat:"c"
        }, {
            name: "StartGPSType",
            type: "int"
        }, {
            name: "EndGPSType",
            type: "int"
        }, {
            name: "StartPic",
            type: "int"
        }, {
            name: "EndPic",
            type: "int"
        }, {
            name: "TaskPriority",
            type: "int"
        }, {
            name: "IsCombin",
            type: "int"
        }, {
            name: "Remark",
            type: "string"
        }, {
            name: "ClientID",
            type: "int"
        }, {
            name: "ClientDistributorID",
            type: "int"
        }, {
            name: "CreateBy",
            type: "int"
        }, {
            name: "CreateTime",
            type: "datetime"
        }, {
            name: "LastUpdateBy",
            type: "int"
        }, {
            name: "LastUpdateTime",
            type: "datetime"
        }, {
            name: "IsDelete",
            type: "int"
        }, {
            name: "POPTypeText",
            type: "string"
        }, {
            name: "ClientPositionText",
            type: "string"
        }, {
            name: "POPCount",
            type: "int"
        }
        ]
    });
}