/* 为了防止任何可能出现的数据丢失问题，您应该先仔细检查此脚本，然后再在数据库设计器的上下文之外运行此脚本。*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LEventSignUp ADD CONSTRAINT
	DF_LEventSignUp_SignUpID DEFAULT newid() FOR SignUpID
GO
ALTER TABLE dbo.LEventSignUp SET (LOCK_ESCALATION = TABLE)
GO
COMMIT