//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JIT.CPOS.BS.WebServices.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.55:8100/AuthService.asmx")]
        public string JITCPos_BS_WebServices_AuthManagerWebServices_AuthService {
            get {
                return ((string)(this["JITCPos_BS_WebServices_AuthManagerWebServices_AuthService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://180.153.154.21:8101/customer/CustomerDataExchangeService.asmx")]
        public string CPOS_BS_WebServices_CustomerDataExchangeWebService_CustomerDataExchangeService {
            get {
                return ((string)(this["CPOS_BS_WebServices_CustomerDataExchangeWebService_CustomerDataExchangeService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sso.chainclouds.com/AuthService.asmx")]
        public string CPOS_BS_WebServices_AuthManagerWebServices_AuthService {
            get {
                return ((string)(this["CPOS_BS_WebServices_AuthManagerWebServices_AuthService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.chainclouds.com/WebServices/ShortUrlChangeService.asmx")]
        public string CPOS_BS_WebServices_ShortUrlChangeService_ShortUrlChangeService {
            get {
                return ((string)(this["CPOS_BS_WebServices_ShortUrlChangeService_ShortUrlChangeService"]));
            }
        }
    }
}
