function InitVE() {
    Ext.define("BrandEntity", {
        extend: "Ext.data.Model",
        fields: [{
            name: "BrandID",
            type: "int"
        }, {
            name: "BrandNo",
            type: "string"
        }, {
            name: "BrandName",
            type: "string"
        }, {
            name: "IsOwner",
            type: "int"
        }, {
            name: "BrandLevel",
            type: "int"
        }, {
            name: "ParentID",
            type: "int"
        }, {
            name: "Remark",
            type: "string"
        }, {
            name: "ParentBrandName",
            type: "string"
        }, {
            name: "BrandCompany",
            type: "string"
        }, {
            name: "ClientID",
            type: "int"
        }, {
            name: "ClientDistributorID",
            type: "int"
        }, {
            name: "CreateBy",
            type: "int"
        }, {
            name: "CreateTime",
            type: "datetime"
        }, {
            name: "LastUpdateBy",
            type: "int"
        }, {
            name: "LastUpdateTime",
            type: "datetime"
        }]
    });
}