//var DetailData = {code:200,description:"操作成功",content:{hasUserAccount:"0",eventId:"121",title:"中欧国际工商学院首席营销官论坛（北京）---数字时代的营销变革",city:"上海",address:"北京市海淀区东北旺西路8号中关村软件园20号楼",contact:"苏小姐010-323232222",email:"alu156@126.com",imageUrl:"images/20130325130742.JPG",timeStr:"2013.3.30 13:00 --4.3 15:00",organizer:"中欧移动互联网协会/中欧电商协会",organizerType:'1',applyCount:"122",checkinCount:'100',buttonType:"1",applyStatus:0,payStatus:0,checkinStatus:0,hasPrize:0,intervalDays:0,isCheckByBind:"0"}} ;
var DetailData = {"content":{"eventId":"42A9F1884428482B866BD4DDDBD6521D","title":"『6月1日、2日』乐活吧六一儿童节特别场——我的六一我做主","city":"上海","address":"浦东新区芳甸路185号大拇指广场2楼216（蓝枪鱼隔壁）","contact":"010-93913922 王小姐","email":"","imageUrl":"images/20130325130742.JPG","timeStr":"2013/5/24 5:00","organizer":"中国农业部","organizerType":"0","applyCount":"0","checkinCount":"0","hasPrize":"0","intervalDays":"9","description":"\n\t    六一的歌儿是甜甜的，六一的笑容是美美的，在这个甜美的日子里，所有的小朋友都是最开心，最快乐的！尤其是在这天能和爸爸妈妈一起欢度儿童节。现在乐活吧特别安排在2013年6月1日、2日一起欢度这段美好的时光\n\n\n\t乐活吧倾力推荐活动！\n\n1 小小烘培师\n\n   根据现场提供的各类烘培模具，让孩子挑选自己喜欢的样式，并且有专特邀的DIY嘉宾前来现场指导，在父母的通力协助下，和孩子们一同制作属于自己的小饼干或者小蛋糕，和孩子一同分享属于属于他们自己的节日和成功的喜悦！（因制作烘焙有时间的等待，故在等待期间，为孩子们准备了喜欢的动画短片，或者可以和其他孩子一起画画）\n\n （所选用的食品原材料经过严格的筛选，保证孩子做的开心，家长吃的放心）\n\n2 我是沙画大师\n\n   更具现场提供的各类沙画模板和材料，让孩子挑选自己喜欢的图片，父母们从旁协助指点或者静心观看，和同年龄的小朋友们互相结合天马行空的想象力和完美的颜色天赋，描绘出属于自己色彩的沙画。\n\n亲子活动节日套餐\n\nA沙画大师，68元/家庭（包含一杯鲜榨果汁和沙画材料，可制作3张）\n\nB 烘培师    108元/家庭（包含一杯鲜榨果汁和模具内的烘培成品，曲奇饼干一组5至6块或者小蛋糕2个任意挑选）\n\nC 三合一套餐 168元/家庭（包含两杯鲜榨果汁+沙画大师+烘培师）另可在店内的KTV点歌台和孩子一同挑选孩子们喜欢的歌曲，一起发挥你们的歌唱才艺）\n\n   即日起至要在微信平台上报名，立减10元，节日当天入店的小朋友们还有各式精美礼品相送，还在等什么呢？赶快和您的孩子们一起报名参加吧！打造属于他们自己的多彩儿童节！更多惊喜，敬请期待～～\n\n  请各位关注乐活吧的朋友们切勿冒失前来，因为每次活动都有不同的特邀嘉宾，如果当天活动人数不足或者过多，本店会相应的做出适当调整。故请各位亲爱的朋友们来之前请先在微信群上回复报名，以便我们统计人数，制定更加完善的计划和精彩的活动安排，谢谢配合。（本次活动的最终解释权归本公司所有）\n\n\n\t \n","longitude":"31.227628","latitude":"121.55872"},"code":"200","description":"操作成功。","exception":null};


var Return_getAccountBind = {code:"200","description":"操作成功","content":{"hasBindWeixin":"1","userName":"asdasd","userId":"238869","isBindSucceed":"1"}};

var Return_login = {"code":"200","description":"操作成功","content":{"hasBindWeixin":"1","userName":"eeee","userId":"238869"}}

var CheckInData = {"code":"200","description":"操作成功","content":{}};
var PriteListData = {"code":"200","content":{"hasPrizeOpen":"1","prizeStatus":"0","hasUserAccount":"1","myPrizes":[],"prizes":[{"imageUrl":"images/images.jpg","prizeDesc":"奖品描述","prizeId":"1","prizeName":"奖品一"},{"imageUrl":"images/images.jpg","prizeDesc":"奖品描述","prizeId":"2","prizeName":"奖品二"},{"imageUrl":"images/images.jpg","prizeDesc":"奖品描述","prizeId":"3","prizeName":"奖品三"},{"imageUrl":"images/images.jpg","prizeDesc":"奖品描述","prizeId":"4","prizeName":"奖品四"}],"type":"0","winnerCount":"0","winners":[]},"description":"操作成功"};
var PriteListData1 = {"code":"200","content":{"hasPrizeOpen":"1","noBindText":"未绑定！","hasUserAccount":"1","myPrizes":[{"imageUrl":"http://i6.hexunimg.cn/2012-10-30/147380755.jpg","poolId":"1","prizeDesc":"奖品描述","prizeId":"1","prizeName":"奖品一"},{"imageUrl":"http://pic4.nipic.com/20091215/1546141_181058005434_2.jpg","poolId":"2","prizeDesc":"奖品描述","prizeId":"1","prizeName":"奖品二"},{"imageUrl":"http://i1.sinaimg.cn/IT/cr/2012/1206/2646343953.jpg","poolId":"3","prizeDesc":"奖品描述","prizeId":"1","prizeName":"奖品三"},{"imageUrl":"http://image.techweb.com.cn/upload/2012/1206/1354780499361.jpg","poolId":"4","prizeDesc":"奖品描述","prizeId":"1","prizeName":"奖品四"}],"prizes":[],"type":"1","winnerCount":"0","winners":[]},"description":"操作成功"};
var PriteListData2 = {"code":"200","content":{"hasPrizeOpen":"1","hasUserAccount":"1","myPrizes":[],"prizes":[],"type":"2","winnerCount":"0","isNext":"1","winners":[{"imageUrl":"images/example.jpg","timeStamp":"1223223232","userDesc":"昆山微讯网信息科技有限公司 ","userInfoEx":"EMBA09SH2","userName":"王孟孟 Vincent"},{"imageUrl":"http://i6.hexunimg.cn/2012-10-30/147380755.jpg","timeStamp":"1223223232","userDesc":"昆山微讯网信息科技有限公司网信息科技有限公司网信息科技有限公司 ","userInfoEx":"EMBA09SH2","userName":"王孟孟 Vincent"},{"imageUrl":"images/example.jpg","timeStamp":"1223223232","userDesc":"昆山微讯网信息科技有限公司网信息科技有限公司网信息科技有限公司 ","userInfoEx":"EMBA09SH2","userName":"王孟孟 Vincent"},{"imageUrl":"images/example.jpg","timeStamp":"1223223232","userDesc":"昆山微讯网信息科技有限公网信息科技有限公司网信息科技有限公司司 ","userInfoEx":"EMBA09SH2","userName":"王孟孟 Vincent"}]},"description":"操作成功"};

var HuDongData = {"code":"200","content":{"hasPollOpen":"0","hasUserAccount":"1","post":[{"commentCount":"33","message":"测试数据1@@@","postId":"234","thumbnailImageUrl":"","timestamp":"2342433434","userImageUrl":"http://img4.duitang.com/uploads/group/201108/19/20110819162254_skL8y.thumb.180_180_c.jpg","userInfoEx":"EMBA08SH2","userName":"王孟孟 Vincent", "time":"5秒前"}]},"description":"操作成功"};

var ShopDetailData = {"code":"200","content":{"address":"云南省丽江市古城区光义街忠义巷174号","description":"花间堂•青尘院位于丽江市古城区光义街忠义巷174号，毗邻丽江古城最具当地生活气息的集市——忠义市场，交通出行十分便利，步行至著名景点木府也仅需3分钟。<\/br>青尘院由主院、辅院、后院三个院落组成，主院宽敞大气，辅院精巧别致，后院宁静优雅。18间精致、唯美的客房与自助餐厅、书房、影音室等公共空间分布其间，各种花卉树木错落环绕，郁郁葱葱，移步易景，景景相透。客房内均配有地暖系统、高档卫浴设施、卫星电视及无线网络，在古朴典雅的纳西院落中，尽享清闲舒适的丽江慢生活。青尘院的另一大特色便是她的自助厨房，借助临近忠义市场这一得天独厚的优势，采买最新鲜地道的当地食材，亲自下厨一展身手，绝对乐在其中。","imageUrl":"http://img1.qunarzz.com/wugc/p207/201305/15/743dcc658d3d878093835fbb.jpg_r_535x400x90_5a16d9ad.jpg","name":"花间堂丽江青尘院体验券","price":"780元/一晚","priceNow":"1元/一晚","telephone":"18988015030"},"description":"操作成功"};

var nearbyData = {"code":"200","content":{"users":[{"distance":"100米","imageUrl":"","tiemStr":"10秒钟前","userDesc":"昆山微讯网信息科技有限公司","userInfoEx":"EMBA08SH2","userName":"王孟孟 Vincent Wang"},{"distance":"1公里","imageUrl":"","tiemStr":"10分钟前","userDesc":"昆山微讯网信息科技有限公司22","userInfoEx":"EMBA08SH2","userName":"王孟孟22 Vincent Wang"},{"distance":"2公里","imageUrl":"","tiemStr":"2013-5-17 14:22","userDesc":"昆山微讯网信息科技有限公司33","userInfoEx":"EMBA08SH2","userName":"王孟孟33 Vincent Wang"},{"distance":"100m","imageUrl":"","tiemStr":"2天前","userDesc":"昆山微讯网信息科技有限公司44","userInfoEx":"EMBA08SH2","userName":"王孟孟44 Vincent Wang"},{"distance":"100m","imageUrl":"","tiemStr":"10秒钟前","userDesc":"昆山微讯网信息科技有限公司55","userInfoEx":"EMBA08SH2","userName":"王孟孟55 Vincent Wang"}]},"description":"操作成功"};

var ApplyData ={"content":{"userName":null,"userId":null,"classValue":null,"mobile":null,"email":null,"questionCount":"6","questions":[{"questionId":"1","isSaveOutEvent":"1","cookieName":"userName","questionText":"小朋友姓名","questionType":"1","minSelected":"0","maxSelected":"0","isRequired":"1","isFinished":"0","options":null},{"questionId":"2","isSaveOutEvent":"1","cookieName":"Patriarch","questionText":"家长联系方式","questionType":"2","minSelected":"0","maxSelected":"0","isRequired":"1","isFinished":"0","options":null},{"questionId":"3","isSaveOutEvent":"0","cookieName":"caa","questionText":"家长陪同人数","questionType":"3","minSelected":"0","maxSelected":"0","isRequired":"1","isFinished":"0","options":[{"optionId":"1","optionText":"1","isSelected":"0"},{"optionId":"2","optionText":"2","isSelected":"0"},{"optionId":"3","optionText":"3","isSelected":"0"},{"optionId":"4","optionText":"4","isSelected":"0"},{"optionId":"5","optionText":"5","isSelected":"0"}]},{"questionId":"4","isSaveOutEvent":"1","cookieName":"Entries","questionText":"报名项目","questionType":"3","minSelected":"0","maxSelected":"0","isRequired":"1","isFinished":"0","options":[{"optionId":"6","optionText":"沙画","isSelected":"0"},{"optionId":"7","optionText":"烘焙","isSelected":"0"},{"optionId":"8","optionText":"沙画烘焙套餐","isSelected":"0"}]},{"questionId":"5","isSaveOutEvent":"1","cookieName":"SelDate","questionText":"选择日期","questionType":"3","minSelected":"0","maxSelected":"0","isRequired":"1","isFinished":"0","options":[{"optionId":"10","optionText":"2013年6月2日","isSelected":"0"},{"optionId":"9","optionText":"2013年6月1日","isSelected":"0"}]},{"questionId":"6","isSaveOutEvent":"1","cookieName":"SelTime","questionText":"选择时间","questionType":"5","minSelected":"0","maxSelected":"0","isRequired":"1","isFinished":"0","options":[{"optionId":"11","optionText":"9：30~11：00","isSelected":"0"},{"optionId":"12","optionText":"12：00~13：30","isSelected":"0"},{"optionId":"13","optionText":"14：00~15：30","isSelected":"0"},{"optionId":"14","optionText":"16：00~17：30","isSelected":"0"}]}]},"code":"200","description":"操作成功。","exception":null}

/*var ApplyData = {"code":"200","description":"操作成功","content":{"userName":"Mrs CHeng","class":"MTL2","mobile":"13816280305","email":"zhanzhongliang@weixun.co","questionCount":"4","questions":[
{"questionId":"106","questionText":"姓名","questionType":"1","minSelected":"1","maxSelected":"2","isRequired":"1","isFinished":"0","IsSaveOutEvent":"0","cookieName":"QuestIon10","options":[]},
{"questionId":"107","questionText":"手机号码","questionType":"1","minSelected":"1","maxSelected":"2","isRequired":"1","isFinished":"0","IsSaveOutEvent":"1","cookieName":"QuestIon9","options":[]},
{"questionId":"108","questionText":"邮箱地址","questionType":"1","minSelected":"1","maxSelected":"2","isRequired":"1","isFinished":"0","IsSaveOutEvent":"1","cookieName":"QuestIon0","options":[]},
{"questionId":"109","questionText":"您是在校生还是毕业生(必填)","questionType":"3","minSelected":"1","maxSelected":"2","isRequired":"1","isFinished":"0","IsSaveOutEvent":"0","cookieName":"QuestIon1","options":[{"optionId":"20","optionText":"在校生","isSelected":"0"},{"optionId":"21","optionText":"毕业生","isSelected":"0"}]},

{"questionId":"110","questionText":"你是先生还是女士？","IsSaveOutEvent":"1","cookieName":"QuestIon2","questionType":"3","minSelected":"1","maxSelected":"1","isRequired":"1","isFinished":"0","options":[{"optionId":"30","optionText":"男士","isSelected":"0"},{"optionId":"31","optionText":"女士","isSelected":"0"}]},

{"questionId":"111","questionText":"你的职业是？","IsSaveOutEvent":"0","cookieName":"QuestIon3","questionType":"4","minSelected":"1","maxSelected":"1","isRequired":"0","isFinished":"0","options":[{"optionId":"40","optionText":"工程师","isSelected":"0"},{"optionId":"41","optionText":"商人","isSelected":"0"},{"optionId":"42","optionText":"自由职业者","isSelected":"0"},{"optionId":"43","optionText":"工作人员","isSelected":"0"},{"optionId":"44","optionText":"其他","isSelected":"0"}]},

{"questionId":"112", "IsSaveOutEvent":"1","cookieName":"QuestIon4","questionText":"你最喜欢的做的事情是？","questionType":"1","minSelected":"1","maxSelected":"1","isRequired":"0","isFinished":"0","options":[]},

{"questionId":"113","IsSaveOutEvent":"1","cookieName":"QuestIon5","questionText":"今天你心情怎么样？","questionType":"2","minSelected":"1","maxSelected":"1","isRequired":"1","isFinished":"0","options":[]}

]}};
*/
